const scenes = [
    {
        image: './scenes/scene-1.webp',
        words: [
            "雨", "あめ", "rain",
            "に", "に", "in, at, on",
            "包まれた", "つつまれた", "wrapped, surrounded",
            "街", "まち", "town, city",
            "。", "。", "Full stop (period)",
            "濡れた", "ぬれた", "wet, damp",
            "靴", "くつ", "shoes",
            "で", "で", "with, by",
            "歩く", "あるく", "to walk",
            "俺", "おれ", "I, me (masculine)",
            "の", "の", "possessive particle",
            "足音", "あしおと", "footsteps",
            "が", "が", "subject marker particle",
            "、", "、", "comma",
            "つるつる", "つるつる", "slippery, smooth",
            "の", "の", "possessive particle",
            "舗道", "ほどう", "pavement, sidewalk",
            "に", "に", "on, to",
            "響く", "ひびく", "to echo, to resound",
            "。", "。", "Full stop (period)",
            "新宿", "しんじゅく", "Shinjuku",
            "の", "の", "possessive particle",
            "ネオン", "ねおん", "neon",
            "が", "が", "subject marker particle",
            "霧", "きり", "fog",
            "の", "の", "possessive particle",
            "中", "なか", "inside, middle",
            "で", "で", "in, at",
            "ぼやけ", "ぼやけ", "blurred, fuzzy",
            "、", "、", "comma",
            "人気", "ひとけ", "signs of people, presence",
            "の", "の", "possessive particle",
            "ない", "ない", "not exist, no",
            "通り", "とおり", "street, road",
            "に", "に", "to, on",
            "幽霊", "ゆうれい", "ghost",
            "のような", "のような", "like, similar to",
            "光", "ひかり", "light",
            "を", "を", "object marker particle",
            "投げかけて", "なげかけて", "to cast, to throw",
            "いた", "いた", "was (past continuous)",
            "。", "。", "Full stop (period)",
            "家路", "いえじ", "way home",
            "を", "を", "object marker particle",
            "急ぐ", "いそぐ", "to hurry",
            "俺", "おれ", "I, me (masculine)",
            "の", "の", "possessive particle",
            "心", "こころ", "heart, mind",
            "を", "を", "object marker particle",
            "、", "、", "comma",
            "乾いた", "かわいた", "dry",
            "部屋", "へや", "room",
            "と", "と", "and",
            "温かい", "あたたかい", "warm",
            "酒", "さけ", "alcohol, sake",
            "の", "の", "possessive particle",
            "誘惑", "ゆうわく", "temptation",
            "が", "が", "subject marker particle",
            "駆り立てる", "かりたてる", "to drive, to urge on",
            "。", "。", "Full stop (period)"
        ]
    },
    {
        image: './scenes/scene-2.webp',
        words: [
            "アパート", "あぱーと", "apartment",
            "の", "の", "possessive particle",
            "前", "まえ", "front",
            "の", "の", "possessive particle",
            "路地", "ろじ", "alley",
            "の", "の", "possessive particle",
            "奥", "おく", "depths, back",
            "から", "から", "from",
            "物音", "ものおと", "noise, sound",
            "が", "が", "subject marker particle",
            "した", "した", "did, happened",
            "。", "。", "Full stop (period)",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "足", "あし", "foot, leg",
            "を", "を", "object marker particle",
            "止め", "とめ", "to stop",
            "、", "、", "comma",
            "ポケット", "ぽけっと", "pocket",
            "の", "の", "possessive particle",
            "ライター", "らいたー", "lighter",
            "に", "に", "to, towards",
            "手", "て", "hand",
            "を", "を", "object marker particle",
            "伸ばす", "のばす", "to extend, to reach out",
            "。", "。", "Full stop (period)",
            "暗闇", "くらやみ", "darkness",
            "から", "から", "from",
            "人影", "ひとかげ", "human figure, silhouette",
            "が", "が", "subject marker particle",
            "現れる", "あらわれる", "to appear",
            "。", "。", "Full stop (period)",
            "男", "おとこ", "man",
            "は", "は", "topic marker particle",
            "帽子", "ぼうし", "hat",
            "を", "を", "object marker particle",
            "目深に", "めぶかに", "low over one's eyes",
            "被り", "かぶり", "to wear (on head)",
            "、", "、", "comma",
            "トレンチコート", "とれんちこーと", "trench coat",
            "の", "の", "possessive particle",
            "襟", "えり", "collar",
            "まで", "まで", "up to, as far as",
            "隠れて", "かくれて", "hidden",
            "いた", "いた", "was (past continuous)",
            "。", "。", "Full stop (period)",
            "タバコ", "たばこ", "cigarette",
            "の", "の", "possessive particle",
            "火", "ひ", "fire, light",
            "が", "が", "subject marker particle",
            "一瞬", "いっしゅん", "moment, instant",
            "顔", "かお", "face",
            "を", "を", "object marker particle",
            "照らし", "てらし", "to illuminate",
            "、", "、", "comma",
            "鋭く", "するどく", "sharp, keen",
            "疲れた", "つかれた", "tired",
            "表情", "ひょうじょう", "expression",
            "が", "が", "subject marker particle",
            "浮かび上がる", "うかびあがる", "to emerge, to appear",
            "。", "。", "Full stop (period)",
            "雨音", "あまおと", "sound of rain",
            "だけ", "だけ", "only, just",
            "が", "が", "subject marker particle",
            "静寂", "せいじゃく", "silence",
            "を", "を", "object marker particle",
            "破って", "やぶって", "breaking",
            "いた", "いた", "was (past continuous)",
            "。", "。", "Full stop (period)"
        ]
    },
    {
        image: './scenes/scene-3.webp',
        words: [
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "前", "まえ", "forward",
            "に", "に", "to, towards",
            "進み", "すすみ", "to advance, to proceed",
            "、", "、", "comma",
            "普段", "ふだん", "usually, normally",
            "より", "より", "than, compared to",
            "急", "きゅう", "steep, sudden",
            "に", "に", "adverbial particle",
            "思える", "おもえる", "to seem, to appear",
            "階段", "かいだん", "stairs",
            "を", "を", "object marker particle",
            "上る", "のぼる", "to climb, to go up",
            "。", "。", "Full stop (period)",
            "上", "うえ", "up, top",
            "に", "に", "to, at",
            "着いた", "ついた", "arrived",
            "とき", "とき", "when, at the time",
            "、", "、", "comma",
            "雨", "あめ", "rain",
            "を", "を", "object marker particle",
            "切り裂く", "きりさく", "to cut through, to rip",
            "ように", "ように", "like, as if",
            "声", "こえ", "voice",
            "が", "が", "subject marker particle",
            "響いた", "ひびいた", "echoed, resounded",
            "。", "。", "Full stop (period)",
            "「手塚", "てづか", "Tezuka (surname)",
            "さん", "さん", "Mr./Ms. (polite suffix)",
            "か", "か", "question particle",
            "？」", "？」", "Question mark and closing quotation",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "ゆっくり", "ゆっくり", "slowly",
            "と", "と", "quotation particle",
            "振り向き", "ふりむき", "to turn around",
            "、", "、", "comma",
            "男", "おとこ", "man",
            "を", "を", "object marker particle",
            "睨みつける", "にらみつける", "to glare at",
            "。", "。", "Full stop (period)",
        ]
    },
    {
        image: './scenes/scene-3.webp',
        words: [
            "「明日", "あした", "tomorrow",
            "いつか", "いつか", "sometime",
            "私", "わたし", "my",
            "の", "の", "possessive particle",
            "オフィス", "おふぃす", "office",
            "に", "に", "to (direction particle)",
            "来て", "きて", "come (imperative)",
            "」", "」", "closing quotation mark",
            "と", "と", "quotation particle",
            "言った", "いった", "said",
            "。", "。", "Full stop (period)",
            "見知らぬ", "みしらぬ", "unknown, unfamiliar",
            "男", "おとこ", "man",
            "の", "の", "possessive particle",
            "目", "め", "eyes",
            "が", "が", "subject marker particle",
            "細く", "ほそく", "narrow, thin",
            "なり", "なり", "to become",
            "、", "、", "comma",
            "明らか", "あきらか", "obvious, clear",
            "に", "に", "adverbial particle",
            "我慢", "がまん", "patience, endurance",
            "の", "の", "possessive particle",
            "限界", "げんかい", "limit",
            "だった", "だった", "was",
            "。", "。", "Full stop (period)"
        ]
    },
    {
        image: './scenes/scene-3.webp',
        words: [
            "「聞け", "きけ", "listen (imperative)",
            "、", "、", "comma",
            "ずっと", "ずっと", "all along, the whole time",
            "外", "そと", "outside",
            "で", "で", "at, in",
            "待って", "まって", "waiting",
            "いた", "いた", "was (past continuous)",
            "んだ", "んだ", "explanatory particle",
            "。", "。", "Full stop (period)",
            "生意気な", "なまいきな", "impertinent, cheeky",
            "口", "くち", "mouth",
            "を", "を", "object marker particle",
            "利く", "きく", "to speak, to talk",
            "な", "な", "negative imperative",
            "。", "。", "Full stop (period)",
            "誰", "だれ", "who, anyone",
            "にも", "にも", "to anyone (emphatic)",
            "知られ", "しられ", "to be known",
            "たくない", "たくない", "don't want",
            "用事", "ようじ", "business, errand",
            "が", "が", "subject marker",
            "ある", "ある", "to have, to exist",
            "。", "。", "period",
            "私", "わたし", "I",
            "は", "は", "topic marker",
            "刑事", "けいじ", "detective",
            "の", "の", "possessive particle",
            "オフィス", "おふぃす", "office",
            "の", "の", "possessive particle",
            "周り", "まわり", "around",
            "で", "で", "at, in (location particle)",
            "見られ", "みられ", "to be seen",
            "ては", "ては", "if (conditional)",
            "いけない", "いけない", "must not",
            "」", "」", "closing quotation mark",
        ]
    },
    {
        image: './scenes/scene-4.webp',
        words: [
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "肩", "かた", "shoulder",
            "を", "を", "object marker particle",
            "すくめ", "すくめ", "to shrug",
            "、", "、", "comma",
            "無関心", "むかんしん", "indifference",
            "を", "を", "object marker particle",
            "装う", "よそおう", "to pretend, to feign",
            "。", "。", "Full stop (period)",
            "「今夜", "こんや", "tonight",
            "は", "は", "topic marker particle",
            "浮気", "うわき", "affair, infidelity",
            "調査", "ちょうさ", "investigation",
            "は", "は", "topic marker particle",
            "ご免", "ごめん", "sorry, no thanks",
            "だ", "だ", "copula (casual)",
            "」", "」", "Closing quotation",
            "男", "おとこ", "man",
            "は", "は", "topic marker particle",
            "俺", "おれ", "I, me (masculine)",
            "の", "の", "possessive particle",
            "言葉", "ことば", "words",
            "を", "を", "object marker particle",
            "無視し", "むしし", "ignore",
            "、", "、", "comma",
            "コート", "こーと", "coat",
            "の", "の", "possessive particle",
            "中", "なか", "inside",
            "から", "から", "from",
            "封筒", "ふうとう", "envelope",
            "を", "を", "object marker particle",
            "取り出した", "とりだした", "took out",
            "。", "。", "Full stop (period)",
            "何年も", "なんねんも", "many years",
            "見て", "みて", "see",
            "いない", "いない", "not, haven't",
            "印章", "いんしょう", "seal, stamp",
            "が", "が", "subject marker particle",
            "ついて", "ついて", "attached",
            "いる", "いる", "to be (continuous)",
            "。", "。", "Full stop (period)",
            "帝国", "ていこく", "imperial",
            "陸軍", "りくぐん", "army",
            "だ", "だ", "copula (casual)",
            "。", "。", "Full stop (period)",
            "心臓", "しんぞう", "heart",
            "が", "が", "subject marker particle",
            "跳ねた", "はねた", "jumped, leaped",
            "が", "が", "but",
            "、", "、", "comma",
            "表情", "ひょうじょう", "expression",
            "は", "は", "topic marker particle",
            "変え", "かえ", "change",
            "なかった", "なかった", "did not",
            "。", "。", "Full stop (period)",
            "「見せて", "みせて", "show me",
            "もらおう", "もらおう", "let's (polite request)",
            "か", "か", "question particle",
            "」", "」", "Closing quotation",
            "と", "と", "quotation particle",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "言った", "いった", "said",
            "。", "。", "Full stop (period)"
        ]
    },
    {
        image: './scenes/scene-4.webp',
        words: [
            "男", "おとこ", "man",
            "が", "が", "subject marker particle",
            "封筒", "ふうとう", "envelope",
            "を", "を", "object marker particle",
            "差し出す", "さしだす", "to offer, to present",
            "。", "。", "Full stop (period)",
            "印章", "いんしょう", "seal, stamp",
            "は", "は", "topic marker particle",
            "間違い", "まちがい", "mistake",
            "なく", "なく", "without",
            "本物", "ほんもの", "genuine, authentic",
            "だ", "だ", "copula (casual)",
            "。", "。", "Full stop (period)",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "男", "おとこ", "man",
            "を", "を", "object marker particle",
            "見返し", "みかえし", "to look back at",
            "、", "、", "comma",
            "興味", "きょうみ", "interest",
            "を", "を", "object marker particle",
            "そそられた", "そそられた", "was aroused, was piqued",
            "。", "。", "Full stop (period)",
            "「よし", "よし", "Alright, OK",
            "」", "」", "Closing quotation",
            "と", "と", "quotation particle",
            "言って", "いって", "saying",
            "、", "、", "comma",
            "脇", "わき", "side",
            "に", "に", "to, towards",
            "寄る", "よる", "to approach, to move closer",
            "。", "。", "Full stop (period)",
            "「入れ", "はいれ", "Come in (imperative)",
            "。", "。", "Full stop (period)",
            "話", "はなし", "story, talk",
            "を", "を", "object marker particle",
            "聞こう", "きこう", "let's hear, let's listen",
            "」", "」", "Closing quotation"
        ]
    },
    {
        image: './scenes/scene-5.webp',
        words: [
            "狭い", "せまい", "narrow, cramped",
            "階段", "かいだん", "stairs",
            "を", "を", "object marker particle",
            "上がり", "あがり", "to go up",
            "、", "、", "comma",
            "アパート", "あぱーと", "apartment",
            "に", "に", "to, towards",
            "案内する", "あんないする", "to guide, to show in",
            "。", "。", "Full stop (period)",
            "大した", "たいした", "great, important",
            "もの", "もの", "thing",
            "じゃない", "じゃない", "is not",
            "が", "が", "but",
            "、", "、", "comma",
            "ここ", "ここ", "here",
            "が", "が", "subject marker particle",
            "俺", "おれ", "I, me (masculine)",
            "の", "の", "possessive particle",
            "城", "しろ", "castle",
            "だ", "だ", "copula (casual)",
            "。", "。", "Full stop (period)",
            "明かり", "あかり", "light",
            "を", "を", "object marker particle",
            "つける", "つける", "to turn on",
            "と", "と", "when, if",
            "、", "、", "comma",
            "散らかった", "ちらかった", "messy, cluttered",
            "小さな", "ちいさな", "small",
            "部屋", "へや", "room",
            "が", "が", "subject marker particle",
            "暖かい", "あたたかい", "warm",
            "光", "ひかり", "light",
            "に", "に", "by, with",
            "包まれた", "つつまれた", "was enveloped",
            "。", "。", "Full stop (period)",
            "いつも", "いつも", "always, as usual",
            "の", "の", "possessive particle",
            "ように", "ように", "like, as",
            "、", "、", "comma",
            "モモ", "もも", "Momo (cat's name)",
            "が", "が", "subject marker particle",
            "俺", "おれ", "I, me (masculine)",
            "の", "の", "possessive particle",
            "足元", "あしもと", "at one's feet",
            "で", "で", "at, in",
            "空腹", "くうふく", "hunger",
            "そう", "そう", "seeming, looking",
            "に", "に", "adverbial particle",
            "鳴いて", "ないて", "meowing",
            "いる", "いる", "to be (continuous)",
            "。", "。", "Full stop (period)",
            "男", "おとこ", "man",
            "に", "に", "to, towards",
            "テーブル", "てーぶる", "table",
            "に", "に", "at, to",
            "座る", "すわる", "to sit",
            "よう", "よう", "in order to",
            "促し", "うながし", "urging, prompting",
            "、", "、", "comma",
            "キッチン", "きっちん", "kitchen",
            "に", "に", "to, towards",
            "向かって", "むかって", "towards",
            "猫缶", "ねこかん", "canned cat food",
            "を", "を", "object marker particle",
            "取り", "とり", "to take, to get",
            "に", "に", "to, for",
            "行く", "いく", "to go"
        ]
    },
    {
        image: './scenes/scene-5.webp',
        words: [
            "キッチン", "きっちん", "kitchen",
            "から", "から", "from",
            "戻る", "もどる", "to return",
            "と", "と", "when",
            "、", "、", "comma",
            "モモ", "もも", "Momo (cat's name)",
            "が", "が", "subject marker particle",
            "俺", "おれ", "I, me (masculine)",
            "の", "の", "possessive particle",
            "足", "あし", "legs",
            "の", "の", "possessive particle",
            "間", "あいだ", "between",
            "を", "を", "object marker particle",
            "すり抜けて", "すりぬけて", "slipping through",
            "いく", "いく", "to go",
            "。", "。", "Full stop (period)",
            "開けた", "あけた", "opened",
            "缶", "かん", "can",
            "を", "を", "object marker particle",
            "、", "、", "comma",
            "キッチン", "きっちん", "kitchen",
            "と", "と", "and",
            "リビング", "りびんぐ", "living room",
            "を", "を", "object marker particle",
            "仕切る", "しきる", "to partition",
            "壁", "かべ", "wall",
            "に沿って", "にそって", "along",
            "並んで", "ならんで", "lined up",
            "いる", "いる", "to be (continuous)",
            "缶", "かん", "can",
            "の", "の", "possessive particle",
            "列", "れつ", "row",
            "に", "に", "to",
            "加える", "くわえる", "to add",
            "。", "。", "Full stop (period)",
            "「飲む", "のむ", "to drink",
            "か", "か", "question particle",
            "？」", "？」", "Question mark and closing quotation",
            "と", "と", "quotation particle",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "尋ねた", "たずねた", "asked",
            "。", "。", "Full stop (period)",
            "「ああ", "ああ", "Yes, yeah",
            "」", "」", "Closing quotation",
            "と", "と", "quotation particle",
            "男", "おとこ", "man",
            "は", "は", "topic marker particle",
            "答えた", "こたえた", "answered",
            "。", "。", "Full stop (period)",
            "グラス", "ぐらす", "glass",
            "を", "を", "object marker particle",
            "二つ", "ふたつ", "two",
            "用意し", "よういし", "prepare",
            "、", "、", "comma",
            "テーブル", "てーぶる", "table",
            "に", "に", "at, to",
            "座る", "すわる", "to sit",
            "。", "。", "Full stop (period)",
            "たっぷり", "たっぷり", "plenty, fully",
            "と", "と", "quotation particle",
            "注いだ", "そそいだ", "poured",
            "グラス", "ぐらす", "glass",
            "を", "を", "object marker particle",
            "一つ", "ひとつ", "one",
            "、", "、", "comma",
            "テーブル", "てーぶる", "table",
            "越し", "ごし", "across",
            "に", "に", "to",
            "男", "おとこ", "man",
            "に", "に", "to",
            "滑らせる", "すべらせる", "to slide",
            "。", "。", "Full stop (period)",
            "「話して", "はなして", "tell, speak",
            "もらおう", "もらおう", "let's have",
            "か", "か", "question particle",
            "」", "」", "Closing quotation",
            "と", "と", "quotation particle",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "言い", "いい", "say",
            "、", "、", "comma",
            "グラス", "ぐらす", "glass",
            "を", "を", "object marker particle",
            "持ち上げる", "もちあげる", "to lift up",
            "。", "。", "Full stop (period)",
            "「何", "なに", "what",
            "の", "の", "possessive particle",
            "用", "よう", "business, matter",
            "だ", "だ", "copula (casual)",
            "？」", "？」", "Question mark and closing quotation"
        ]
    },
    {
        image: './scenes/scene-6.webp',
        words: [
            "男", "おとこ", "man",
            "は", "は", "topic marker particle",
            "一口", "ひとくち", "one sip",
            "飲み", "のみ", "to drink",
            "、", "、", "comma",
            "肩", "かた", "shoulder",
            "の", "の", "possessive particle",
            "力", "ちから", "strength",
            "が", "が", "subject marker particle",
            "少し", "すこし", "a little",
            "抜けた", "ぬけた", "relaxed, eased",
            "よう", "よう", "seeming",
            "だった", "だった", "was",
            "。", "。", "Full stop (period)",
            "「俺", "おれ", "I, me (masculine)",
            "から", "から", "from",
            "は", "は", "topic marker particle",
            "話す", "はなす", "to talk",
            "こと", "こと", "thing",
            "は", "は", "topic marker particle",
            "あまり", "あまり", "not much",
            "ない", "ない", "not exist",
            "」", "」", "Closing quotation",
            "グラス", "ぐらす", "glass",
            "を", "を", "object marker particle",
            "片手", "かたて", "one hand",
            "で", "で", "with",
            "置き", "おき", "to put down",
            "ながら", "ながら", "while",
            "、", "、", "comma",
            "もう", "もう", "other",
            "片方", "かたほう", "one side",
            "の", "の", "possessive particle",
            "手", "て", "hand",
            "で", "で", "with",
            "封筒", "ふうとう", "envelope",
            "を", "を", "object marker particle",
            "テーブル", "てーぶる", "table",
            "から", "から", "from",
            "持ち上げ", "もちあげ", "lift up",
            "、", "、", "comma",
            "俺", "おれ", "I, me (masculine)",
            "の", "の", "possessive particle",
            "方", "ほう", "direction",
            "に", "に", "towards",
            "滑らせる", "すべらせる", "to slide",
            "。", "。", "Full stop (period)",
            "「この", "この", "this",
            "封筒", "ふうとう", "envelope",
            "に", "に", "in",
            "住所", "じゅうしょ", "address",
            "が", "が", "subject marker particle",
            "書いて", "かいて", "written",
            "ある", "ある", "to exist",
            "。", "。", "Full stop (period)",
            "彼", "かれ", "he",
            "が", "が", "subject marker particle",
            "明日", "あした", "tomorrow",
            "、", "、", "comma",
            "直接", "ちょくせつ", "directly",
            "話", "はなし", "talk",
            "を", "を", "object marker particle",
            "したい", "したい", "want to do",
            "そう", "そう", "it seems",
            "だ", "だ", "copula (casual)",
            "」", "」", "Closing quotation",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "一瞬", "いっしゅん", "moment",
            "躊躇して", "ちゅうちょして", "hesitating",
            "から", "から", "after",
            "手", "て", "hand",
            "を", "を", "object marker particle",
            "伸ばし", "のばし", "extend",
            "、", "、", "comma",
            "封筒", "ふうとう", "envelope",
            "を", "を", "object marker particle",
            "テーブル", "てーぶる", "table",
            "の", "の", "possessive particle",
            "自分", "じぶん", "oneself",
            "の", "の", "possessive particle",
            "側", "がわ", "side",
            "に", "に", "to",
            "引き寄せた", "ひきよせた", "pulled towards",
            "。", "。", "Full stop (period)",
            "モモ", "もも", "Momo (cat's name)",
            "が", "が", "subject marker particle",
            "テーブル", "てーぶる", "table",
            "に", "に", "onto",
            "飛び乗り", "とびのり", "jump on",
            "、", "、", "comma",
            "好奇心", "こうきしん", "curiosity",
            "旺盛", "おうせい", "strong, vigorous",
            "に", "に", "adverbial particle",
            "封筒", "ふうとう", "envelope",
            "の", "の", "possessive particle",
            "匂い", "におい", "smell",
            "を", "を", "object marker particle",
            "嗅ぎ", "かぎ", "to sniff",
            "始める", "はじめる", "to begin"
        ]
    },
    {
        image: './scenes/scene-6.webp',
        words: [
            "「明日", "あした", "tomorrow",
            "は", "は", "topic marker particle",
            "忙しい", "いそがしい", "busy",
            "んだ", "んだ", "explanatory particle",
            "が", "が", "but",
            "、", "、", "comma",
            "何", "なに", "what",
            "の", "の", "possessive particle",
            "話", "はなし", "talk, story",
            "だ", "だ", "copula (casual)",
            "？」", "？」", "Question mark and closing quotation",
            "と", "と", "quotation particle",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "尋ね", "たずね", "to ask",
            "、", "、", "comma",
            "モモ", "もも", "Momo (cat's name)",
            "を", "を", "object marker particle",
            "優しく", "やさしく", "gently",
            "追い払う", "おいはらう", "to shoo away",
            "。", "。", "Full stop (period)",
            "男", "おとこ", "man",
            "は", "は", "topic marker particle",
            "空", "から", "empty",
            "の", "の", "possessive particle",
            "グラス", "ぐらす", "glass",
            "に", "に", "on",
            "手", "て", "hand",
            "を", "を", "object marker particle",
            "置いた", "おいた", "placed",
            "まま", "まま", "as is, leaving",
            "黙って", "だまって", "silently",
            "いた", "いた", "was (past continuous)",
            "。", "。", "Full stop (period)",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "話し", "はなし", "talking",
            "ながら", "ながら", "while",
            "封筒", "ふうとう", "envelope",
            "を", "を", "object marker particle",
            "開け", "あけ", "to open",
            "、", "、", "comma",
            "中身", "なかみ", "contents",
            "を", "を", "object marker particle",
            "ちらり", "ちらり", "glance",
            "と", "と", "quotation particle",
            "見る", "みる", "to see, to look",
            "。", "。", "Full stop (period)",
            "「彼", "かれ", "he",
            "は", "は", "topic marker particle",
            "直接", "ちょくせつ", "directly",
            "話したい", "はなしたい", "want to talk",
            "らしい", "らしい", "it seems",
            "が", "が", "but",
            "、", "、", "comma",
            "家族", "かぞく", "family",
            "に関する", "にかんする", "regarding, concerning",
            "何か", "なにか", "something",
            "だ", "だ", "copula (casual)",
            "そう", "そう", "it seems",
            "だ", "だ", "copula (casual)",
            "」", "」", "Closing quotation",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "その", "その", "that",
            "住所", "じゅうしょ", "address",
            "を", "を", "object marker particle",
            "知って", "しって", "to know",
            "いた", "いた", "was (past continuous)",
            "。", "。", "Full stop (period)",
            "これ以上", "これいじょう", "more than this",
            "質問", "しつもん", "question",
            "する", "する", "to do",
            "必要", "ひつよう", "need",
            "は", "は", "topic marker particle",
            "なかった", "なかった", "did not exist",
            "。", "。", "Full stop (period)",
            "ある", "ある", "certain",
            "勲章", "くんしょう", "medal, decoration",
            "持ち", "もち", "holder",
            "の", "の", "possessive particle",
            "将軍", "しょうぐん", "general",
            "の", "の", "possessive particle",
            "屋敷", "やしき", "mansion, estate",
            "が", "が", "subject marker particle",
            "ある", "ある", "to exist",
            "地域", "ちいき", "area, region",
            "だ", "だ", "copula (casual)",
            "。", "。", "Full stop (period)",
            "封筒", "ふうとう", "envelope",
            "の", "の", "possessive particle",
            "印章", "いんしょう", "seal, stamp",
            "を", "を", "object marker particle",
            "考えれば", "かんがえれば", "if one considers",
            "、", "、", "comma",
            "偶然", "ぐうぜん", "coincidence",
            "じゃない", "じゃない", "is not",
            "だろう", "だろう", "probably"
        ]
    },
    {
        image: './scenes/scene-7.webp',
        words: [
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "背もたれ", "せもたれ", "backrest",
            "に", "に", "to",
            "寄りかかり", "よりかかり", "leaning against",
            "、", "、", "comma",
            "グラス", "ぐらす", "glass",
            "の", "の", "possessive particle",
            "中", "なか", "inside",
            "の", "の", "possessive particle",
            "ウイスキー", "うぃすきー", "whiskey",
            "を", "を", "object marker particle",
            "揺らす", "ゆらす", "to swirl",
            "。", "。", "Full stop (period)",
            "「わかった", "わかった", "I understand",
            "。", "。", "Full stop (period)",
            "明日", "あした", "tomorrow",
            "の", "の", "possessive particle",
            "朝", "あさ", "morning",
            "に", "に", "at",
            "行く", "いく", "to go",
            "よ", "よ", "emphatic particle",
            "。", "。", "Full stop (period)",
            "それにしても", "それにしても", "even so, nevertheless",
            "、", "、", "comma",
            "お前", "おまえ", "you (informal)",
            "は", "は", "topic marker particle",
            "何", "なに", "what",
            "の", "の", "possessive particle",
            "仕事", "しごと", "job, work",
            "だ", "だ", "copula (casual)",
            "？", "？", "Question mark",
            "こんな", "こんな", "such, like this",
            "夜遅く", "よるおそく", "late at night",
            "に", "に", "at",
            "俺", "おれ", "I, me (masculine)",
            "の", "の", "possessive particle",
            "家", "いえ", "house",
            "の", "の", "possessive particle",
            "前", "まえ", "front",
            "で", "で", "at",
            "待って", "まって", "waiting",
            "いる", "いる", "to be (continuous)",
            "なんて", "なんて", "such as, like",
            "」", "」", "Closing quotation",
            "「彼", "かれ", "he",
            "の", "の", "possessive particle",
            "運転手", "うんてんしゅ", "driver",
            "だ", "だ", "copula (casual)",
            "」", "」", "Closing quotation",
            "と", "と", "quotation particle",
            "男", "おとこ", "man",
            "は", "は", "topic marker particle",
            "答えた", "こたえた", "answered",
            "。", "。", "Full stop (period)",
            "俺", "おれ", "I, me (masculine)",
            "が", "が", "subject marker particle",
            "帰り道", "かえりみち", "way home",
            "用", "よう", "for the purpose of",
            "に", "に", "for",
            "もう", "もう", "another",
            "一杯", "いっぱい", "one glass",
            "グラス", "ぐらす", "glass",
            "に", "に", "into",
            "注ぐ", "そそぐ", "to pour",
            "と", "と", "when, as"
        ]
    },
    {
        image: './scenes/scene-7.webp',
        words: [
            "「寄って", "よって", "to stop by",
            "くれて", "くれて", "giving me (the favor of)",
            "ありがとう", "ありがとう", "thank you",
            "。", "。", "Full stop (period)",
            "明日", "あした", "tomorrow",
            "、", "、", "comma",
            "将軍", "しょうぐん", "general",
            "の", "の", "possessive particle",
            "家", "いえ", "house",
            "に", "に", "to",
            "行く", "いく", "to go",
            "よ", "よ", "emphatic particle",
            "」", "」", "Closing quotation",
            "俺", "おれ", "I, me (masculine)",
            "は", "は", "topic marker particle",
            "言った", "いった", "say",
            "。", "。", "Full stop (period)",
            "男", "おとこ", "man",
            "は", "は", "topic marker particle",
            "飲み物", "のみもの", "drink",
            "を", "を", "object marker particle",
            "受け取り", "うけとり", "to receive",
            "、", "、", "comma",
            "俺", "おれ", "I, me (masculine)",
            "が", "が", "subject marker particle",
            "開けた", "あけた", "opened",
            "ドア", "どあ", "door",
            "を", "を", "object marker particle",
            "通って", "とおって", "passing through",
            "出て", "でて", "to go out",
            "行った", "いった", "went",
            "。", "。", "Full stop (period)",
            "雨", "あめ", "rain",
            "の", "の", "possessive particle",
            "中", "なか", "inside, midst",
            "に", "に", "into",
            "消えて", "きえて", "disappearing",
            "いく", "いく", "to go",
            "男", "おとこ", "man",
            "を", "を", "object marker particle",
            "見送り", "みおくり", "seeing off",
            "ながら", "ながら", "while",
            "、", "、", "comma",
            "この", "この", "this",
            "仕事", "しごと", "job, work",
            "が", "が", "subject marker particle",
            "簡単", "かんたん", "simple, easy",
            "には", "には", "adverbial particle",
            "済まない", "すまない", "won't end up",
            "という", "という", "called, named",
            "予感", "よかん", "premonition",
            "が", "が", "subject marker particle",
            "消え", "きえ", "to disappear",
            "なかった", "なかった", "did not",
            "。", "。", "Full stop (period)"
        ]
    }

];

function convertToJSONFormat(scene) {
    const convertedScene = { ...scene };
    convertedScene.words = [];

    for (let i = 0; i < scene.words.length; i += 3) {
        convertedScene.words.push({
            word: scene.words[i],
            reading: scene.words[i + 1],
            definition: scene.words[i + 2]
        });
    }

    return convertedScene;
}

