
const compactSentences = {
    "LEVEL-1": [
        ["Numbers",
            "二", "に", "Two",
            "四", "よん/し", "Four",
            "一", "いち", "One",
            "五", "ご", "Five",
            "七", "なな/しち", "Seven",
            "九", "きゅう/く", "Nine",
            "三", "さん", "Three",
            "六", "ろく", "Six",
            "八", "はち", "Eight",
        ],
        ["Colors",
            "赤", "あか", "Red",
            "青", "あお", "Blue",
            "黄色", "きいろ", "Yellow",
            "緑", "みどり", "Green",
            "紫", "むらさき", "Purple",
            "茶色", "ちゃいろ", "Brown",
            "白", "しろ", "White",
            "黒", "くろ", "Black",
            "ピンク", "ぴんく", "Pink"
        ],
        ["Family Members",
            "父", "ちち", "Father",
            "母", "はは", "Mother",
            "兄", "あに", "Older brother",
            "姉", "あね", "Older sister",
            "弟", "おとうと", "Younger brother",
            "妹", "いもうと", "Younger sister",
            "祖父", "そふ", "Grandfather",
            "祖母", "そぼ", "Grandmother",
            "子供", "こども", "Child"
        ],
        ["Common Objects",
            "本", "ほん", "Book",
            "鉛筆", "えんぴつ", "Pencil",
            "椅子", "いす", "Chair",
            "机", "つくえ", "Desk",
            "電話", "でんわ", "Telephone",
            "時計", "とけい", "Clock",
            "傘", "かさ", "Umbrella",
            "鍵", "かぎ", "Key",
            "財布", "さいふ", "Wallet"
        ],
        ["Basic Verbs",
            "食べる", "たべる", "To eat",
            "飲む", "のむ", "To drink",
            "見る", "みる", "To see",
            "聞く", "きく", "To hear/listen",
            "話す", "はなす", "To speak",
            "行く", "いく", "To go",
            "来る", "くる", "To come",
            "する", "する", "To do",
            "寝る", "ねる", "To sleep"
        ],
        ["Days of the Week",
            "火曜日", "かようび", "Tuesday",
            "月曜日", "げつようび", "Monday",
            "木曜日", "もくようび", "Thursday",
            "水曜日", "すいようび", "Wednesday",
            "今日", "きょう", "Today",
            "土曜日", "どようび", "Saturday",
            "日曜日", "にちようび", "Sunday",
            "金曜日", "きんようび", "Friday",
            "明日", "あした", "Tomorrow"
        ],
        ["Basic Adjectives",
            "大きい", "おおきい", "Big",
            "小さい", "ちいさい", "Small",
            "長い", "ながい", "Long",
            "短い", "みじかい", "Short",
            "高い", "たかい", "Tall/Expensive",
            "安い", "やすい", "Cheap",
            "新しい", "あたらしい", "New",
            "古い", "ふるい", "Old",
            "良い", "よい/いい", "Good"
        ],
        ["Basic Food Items",
            "ご飯", "ごはん", "Rice/Meal",
            "パン", "ぱん", "Bread",
            "肉", "にく", "Meat",
            "魚", "さかな", "Fish",
            "野菜", "やさい", "Vegetables",
            "果物", "くだもの", "Fruit",
            "水", "みず", "Water",
            "お茶", "おちゃ", "Tea",
            "コーヒー", "こーひー", "Coffee"
        ],
        ["Body Parts",
            "頭", "あたま", "Head",
            "目", "め", "Eye",
            "耳", "みみ", "Ear",
            "口", "くち", "Mouth",
            "鼻", "はな", "Nose",
            "手", "て", "Hand",
            "足", "あし", "Foot/Leg",
            "腕", "うで", "Arm",
            "指", "ゆび", "Finger"
        ],
        ["Weather",
            "晴れ", "はれ", "Sunny",
            "雨", "あめ", "Rain",
            "曇り", "くもり", "Cloudy",
            "雪", "ゆき", "Snow",
            "風", "かぜ", "Wind",
            "暑い", "あつい", "Hot (weather)",
            "寒い", "さむい", "Cold (weather)",
            "涼しい", "すずしい", "Cool",
            "暖かい", "あたたかい", "Warm"
        ],
        ["Occupations",
            "先生", "せんせい", "Teacher",
            "学生", "がくせい", "Student",
            "医者", "いしゃ", "Doctor",
            "看護師", "かんごし", "Nurse",
            "警察官", "けいさつかん", "Police officer",
            "会社員", "かいしゃいん", "Company employee",
            "店員", "てんいん", "Shop clerk",
            "料理人", "りょうりにん", "Chef",
            "運転手", "うんてんしゅ", "Driver"
        ],
        ["Transportation",
            "車", "くるま", "Car",
            "電車", "でんしゃ", "Train",
            "バス", "ばす", "Bus",
            "地下鉄", "ちかてつ", "Subway",
            "タクシー", "たくしー", "Taxi",
            "自転車", "じてんしゃ", "Bicycle",
            "飛行機", "ひこうき", "Airplane",
            "船", "ふね", "Ship",
            "バイク", "ばいく", "Motorcycle"
        ],
        ["Time Expressions",
            "夜", "よる", "Night",
            "今", "いま", "Now",
            "昼", "ひる", "Noon/Daytime",
            "後", "あと", "Later",
            "前", "まえ", "Before",
            "朝", "あさ", "Morning",
            "毎日", "まいにち", "Every day",
            "時々", "ときどき", "Sometimes",
            "すぐ", "すぐ", "Immediately"
        ],
        ["Animals",
            "犬", "いぬ", "Dog",
            "猫", "ねこ", "Cat",
            "鳥", "とり", "Bird",
            "魚", "さかな", "Fish",
            "馬", "うま", "Horse",
            "牛", "うし", "Cow",
            "豚", "ぶた", "Pig",
            "鶏", "にわとり", "Chicken",
            "兎", "うさぎ", "Rabbit"
        ],
        ["Places",
            "家", "いえ/うち", "House/Home",
            "学校", "がっこう", "School",
            "会社", "かいしゃ", "Company",
            "病院", "びょういん", "Hospital",
            "銀行", "ぎんこう", "Bank",
            "郵便局", "ゆうびんきょく", "Post office",
            "図書館", "としょかん", "Library",
            "公園", "こうえん", "Park",
            "駅", "えき", "Station"
        ],
        ["Directions",
            "上", "うえ", "Up/Above",
            "下", "した", "Down/Below",
            "左", "ひだり", "Left",
            "右", "みぎ", "Right",
            "前", "まえ", "Front",
            "後ろ", "うしろ", "Back",
            "中", "なか", "Inside",
            "外", "そと", "Outside",
            "近く", "ちかく", "Near"
        ],
        ["Emotions",
            "嬉しい", "うれしい", "Happy",
            "悲しい", "かなしい", "Sad",
            "楽しい", "たのしい", "Fun/Enjoyable",
            "怒る", "おこる", "Angry",
            "心配", "しんぱい", "Worried",
            "疲れた", "つかれた", "Tired",
            "寂しい", "さびしい", "Lonely",
            "怖い", "こわい", "Scared",
            "驚いた", "おどろいた", "Surprised"
        ],
        ["Household Items",
            "テレビ", "てれび", "Television",
            "冷蔵庫", "れいぞうこ", "Refrigerator",
            "洗濯機", "せんたくき", "Washing machine",
            "電\n子レンジ", "でんしれんじ", "Microwave",
            "エアコン", "えあこん", "Air conditioner",
            "掃除機", "そうじき", "Vacuum cleaner",
            "ベッド", "べっど", "Bed",
            "ソファー", "そふぁー", "Sofa",
            "カーテン", "かーてん", "Curtain"
        ],
        ["Clothing",
            "服", "ふく", "Clothes",
            "シャツ", "しゃつ", "Shirt",
            "ズボン", "ずぼん", "Pants",
            "スカート", "すかーと", "Skirt",
            "靴", "くつ", "Shoes",
            "靴下", "くつした", "Socks",
            "帽子", "ぼうし", "Hat",
            "コート", "こーと", "Coat",
            "セーター", "せーたー", "Sweater"
        ]
    ]
};

function sentenceToJSON(arr) {
    return arr.map(sentence => {
        let result = [];
        for (let i = 1; i < sentence.length - 1; i += 3) {
            result.push({ word: sentence[i], reading: sentence[i + 1], definition: sentence[i + 2] });
        }
        return { category: sentence[0], words: result };
    });
}
