function sentenceToJSON(compactSentences) {
    return compactSentences.map(sentence => {
        let result = [];
        for (let i = 0; i < sentence.length - 4; i += 4) {
            result.push({ word: sentence[i], reading: sentence[i + 1], definition: sentence[i + 2], mask: sentence[i + 3].length === 0 });
        }
        return { words: result, translation: sentence[sentence.length - 1] };
    });
}

const compactSentences =
{
    "LEVEL-1": [
        [
            "私", "わたし", "I", "",
            "は", "", "topic marker", "no-mask",
            "毎朝", "まいあさ", "every morning", "",
            "コーヒー", "こーひー", "coffee", "",
            "を", "", "object marker", "no-mask",
            "飲みます", "のみます", "drink", "",
            "I drink coffee every morning."
        ],
        [
            "彼女", "かのじょ", "she", "",
            "の", "", "possessive particle", "no-mask",
            "猫", "ねこ", "cat", "",
            "は", "", "topic marker", "no-mask",
            "かわいい", "", "cute", "",
            "Her cat is cute."
        ],
        [
            "日曜日", "にちようび", "Sunday", "",
            "に", "", "time particle", "no-mask",
            "公園", "こうえん", "park", "",
            "で", "", "location particle", "no-mask",
            "遊びましょう", "あそびましょう", "let's play", "",
            "Let's play in the park on Sunday."
        ],
        [
            "このペン", "このぺん", "this pen", "",
            "は", "", "topic marker", "no-mask",
            "青い", "あおい", "blue", "",
            "です", "", "is", "no-mask",
            "This pen is blue."
        ],
        [
            "来月", "らいげつ", "next month", "",
            "日本", "にほん", "Japan", "",
            "に", "", "to", "no-mask",
            "行きます", "いきます", "go", "",
            "I will go to Japan next month."
        ],
        [
            "私", "わたし", "I", "",
            "も", "", "also", "no-mask",
            "行きたい", "いきたい", "want to go", "",
            "です", "", "is", "no-mask",
            "I also want to go."
        ],
        [
            "駅", "えき", "station", "",
            "は", "", "topic marker", "no-mask",
            "ここ", "", "here", "",
            "から", "", "from", "no-mask",
            "近い", "ちかい", "near", "",
            "です", "", "is", "no-mask",
            "The station is near from here."
        ],
        [
            "昨日", "きのう", "yesterday", "",
            "友達", "ともだち", "friend", "",
            "と", "", "with", "no-mask",
            "映画", "えいが", "movie", "",
            "を", "", "object marker", "no-mask",
            "見ました", "みました", "watched", "",
            "I watched a movie with a friend yesterday."
        ],
        [
            "私", "わたし", "I", "",
            "の", "", "possessive particle", "no-mask",
            "誕生日", "たんじょうび", "birthday", "",
            "は", "", "topic marker", "no-mask",
            "五月", "ごがつ", "May", "",
            "です", "", "is", "no-mask",
            "My birthday is in May."
        ],
        [
            "日本語", "にほんご", "Japanese language", "",
            "が", "", "subject marker", "no-mask",
            "上手", "じょうず", "good at", "",
            "に", "", "to", "no-mask",
            "なりたい", "", "want (to) become", "",
            "I want to become good at Japanese."
        ],
        [
            "毎晩", "まいばん", "every night", "",
            "十時", "じゅうじ", "10 o'clock", "",
            "に", "", "at", "no-mask",
            "寝ます", "ねます", "sleep", "",
            "I go to sleep at 10 o'clock every night."
        ],
        [
            "週末", "しゅうまつ", "weekend", "",
            "に", "", "on", "no-mask",
            "何", "なに", "what", "",
            "を", "", "object marker", "no-mask",
            "しますか", "", "do you do?", "",
            "What do you do on weekends?"
        ],
        [
            "このりんご", "", "this apple", "",
            "は", "", "topic marker", "no-mask",
            "甘くない", "あまくない", "not sweet", "",
            "です", "", "is", "no-mask",
            "This apple is not sweet."
        ],
        [
            "家", "いえ", "home", "",
            "に", "", "to", "no-mask",
            "帰る", "かえる", "return", "",
            "時間", "じかん", "time", "",
            "です", "", "is", "no-mask",
            "It's time to return home."
        ],
        [
            "電車", "でんしゃ", "train", "",
            "で", "", "by", "no-mask",
            "学校", "がっこう", "school", "",
            "へ", "", "to", "no-mask",
            "行きます", "いきます", "go", "",
            "I go to school by train."
        ],
        [
            "今日", "きょう", "today", "",
            "は", "", "topic marker", "no-mask",
            "とても", "", "very", "",
            "暑い", "あつい", "hot", "",
            "です", "", "is", "no-mask",
            "Today is very hot."
        ],
        [
            "ゆっくり", "", "slowly", "",
            "話して", "はなして", "speak", "",
            "ください", "", "please", "no-mask",
            "Please speak slowly."
        ],
        [
            "水", "みず", "water", "",
            "を", "", "object marker", "no-mask",
            "飲みたい", "のみたい", "want to drink", "",
            "です", "", "is", "no-mask",
            "I want to drink water."
        ],
        [
            "明日", "あした", "tomorrow", "",
            "雨", "あめ", "rain", "",
            "が", "", "subject marker", "no-mask",
            "降る", "ふる", "fall", "",
            "かもしれません", "", "might", "",
            "It might rain tomorrow."
        ],
        [
            "昼ごはん", "ひるごはん", "lunch", "",
            "を", "", "object marker", "no-mask",
            "食べましょう", "たべましょう", "let's eat", "",
            "Let's eat lunch."
        ],
        [
            "日本", "にほん", "Japan", "",
            "に", "", "in", "no-mask",
            "住んで", "すんで", "live", "",
            "います", "", "am", "no-mask",
            "I live in Japan."
        ],
        [
            "今", "いま", "now", "",
            "何時", "なんじ", "what time", "",
            "ですか", "", "is it?", "no-mask",
            "What time is it now?"
        ],
        [
            "彼", "かれ", "he", "",
            "は", "", "topic marker", "no-mask",
            "先生", "せんせい", "teacher", "",
            "ではありません", "", "is not", "",
            "He is not a teacher."
        ],
        [
            "あの人", "あのひと", "that person", "",
            "は", "", "topic marker", "no-mask",
            "だれ", "", "who", "",
            "ですか", "", "is?", "no-mask",
            "Who is that person?"
        ],
    ],

    "LEVEL-2": [
        [
            "宿題", "しゅくだい", "homework", "",
            "を", "", "object marker", "no-mask",
            "やって", "", "do", "",
            "しまいました", "", "completed", "",
            "か", "", "question particle", "no-mask",
            "Have you completed your homework?"
        ],
        [
            "映画", "えいが", "movie", "",
            "を", "", "object marker", "no-mask",
            "見に", "みに", "to watch", "",
            "行こう", "いこう", "let's go", "",
            "と", "", "quotation particle", "no-mask",
            "思う", "おもう", "think", "",
            "I think we should go watch a movie."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "が", "", "subject marker", "no-mask",
            "上手に", "じょうずに", "skillfully", "",
            "話せる", "はなせる", "can speak", "",
            "ようになりたい", "", "want to become able to", "",
            "I want to become able to speak Japanese skillfully."
        ],
        [
            "新しい", "あたらしい", "new", "",
            "仕事", "しごと", "job", "",
            "を", "", "object marker", "no-mask",
            "始める", "はじめる", "start", "",
            "ことに", "", "to do", "",
            "なりました", "", "became", "",
            "I've decided to start a new job."
        ],
        [
            "雨", "あめ", "rain", "",
            "が", "", "subject marker", "no-mask",
            "降る", "ふる", "fall", "",
            "かもしれない", "", "might", "no-mask",
            "It might rain."
        ],
        [
            "傘", "かさ", "umbrella", "",
            "を", "", "object marker", "no-mask",
            "持って", "もって", "bring", "",
            "いった", "", "went", "",
            "ほうが", "", "it would be better if", "",
            "いい", "", "good", "",
            "You'd better bring an umbrella."
        ],
        [
            "この", "", "this", "",
            "本", "ほん", "book", "",
            "を", "", "object marker", "no-mask",
            "読んで", "よんで", "read", "",
            "みませんか", "", "won't you try", "",
            "Why don't you try reading this book?"
        ],
        [
            "友達", "ともだち", "friend", "",
            "に", "", "to", "no-mask",
            "会う", "あう", "meet", "",
            "はず", "", "supposed to", "",
            "だった", "", "was", "",
            "I was supposed to meet my friend."
        ],
        [
            "ゆっくり", "", "slowly", "",
            "話して", "はなして", "speak", "",
            "ください", "", "please", "",
            "Please speak slowly."
        ],
        [
            "宿題", "しゅくだい", "homework", "",
            "を", "", "object marker", "no-mask",
            "忘れて", "わすれて", "forget", "",
            "しまいました", "", "regrettably did", "",
            "I regrettably forgot my homework."
        ],
        [
            "明日", "あした", "tomorrow", "",
            "までに", "", "by", "",
            "レポート", "れぽーと", "report", "",
            "を", "", "object marker", "no-mask",
            "書かなければ", "かかなければ", "must write", "",
            "ならない", "", "have to", "",
            "I have to write the report by tomorrow."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "テスト", "てすと", "test", "",
            "の", "", "possessive particle", "no-mask",
            "準備", "じゅんび", "preparation", "",
            "を", "", "object marker", "no-mask",
            "して", "", "do", "",
            "おきた", "", "did in advance", "",
            "I've prepared for the Japanese test in advance."
        ],
        [
            "彼", "かれ", "he", "",
            "は", "", "topic marker", "no-mask",
            "来る", "くる", "come", "",
            "そう", "", "(I) heard", "",
            "です", "", "politeness marker", "no-mask",
            "I heard he's coming."
        ],
        [
            "映画", "えいが", "movie", "",
            "を", "", "object marker", "no-mask",
            "見", "み", "watch", "",
            "ながら", "", "while", "",
            "寝て", "ねて", "sleep", "",
            "しまった", "", "ended up", "",
            "I ended up falling asleep while watching the movie."
        ],
        [
            "どの", "", "which", "",
            "レストラン", "れすとらん", "restaurant", "",
            "に", "", "to", "no-mask",
            "行きたい", "いきたい", "want to go", "",
            "ですか", "", "question", "no-mask",
            "Which restaurant do you want to go to?"
        ],
        [
            "今日", "きょう", "today", "",
            "は", "", "topic marker", "no-mask",
            "とても", "", "very", "",
            "疲れて", "つかれて", "tired", "",
            "いる", "", "am", "",
            "みたいです", "", "seems like", "",
            "It seems like I'm very tired today."
        ],
        [
            "日本", "にほん", "Japan", "",
            "に", "", "to", "no-mask",
            "行った", "いった", "went", "",
            "こと", "", "nominalizer", "",
            "が", "", "subject marker", "no-mask",
            "ありますか", "", "have you", "",
            "Have you ever been to Japan?"
        ],
        [
            "新しい", "あたらしい", "new", "",
            "言葉", "ことば", "words", "",
            "を", "", "object marker", "no-mask",
            "覚えよう", "おぼえよう", "let's memorize", "",
            "と", "", "quotation particle", "no-mask",
            "思います", "おもいます", "think", "",
            "I think we should try to memorize new words."
        ],
        [
            "電車", "でんしゃ", "train", "",
            "に", "", "on", "no-mask",
            "乗り", "のり", "ride", "",
            "遅れて", "おくれて", "late", "",
            "しまいました", "", "ended up", "",
            "I ended up being late for the train."
        ],
        [
            "この", "", "this", "",
            "料理", "りょうり", "dish", "",
            "は", "", "topic marker", "no-mask",
            "おいしい", "", "delicious", "",
            "そう", "", "looks", "no-mask",
            "This dish looks delicious."
        ],
        [
            "明日", "あした", "tomorrow", "",
            "の", "", "possessive particle", "no-mask",
            "天気", "てんき", "weather", "",
            "は", "", "topic marker", "no-mask",
            "どう", "", "how", "",
            "でしょうか", "", "I wonder", "",
            "I wonder what the weather will be like tomorrow."
        ],
        [
            "コーヒー", "こーひー", "coffee", "",
            "を", "", "object marker", "no-mask",
            "飲み", "のみ", "drink", "",
            "すぎて", "", "too much", "",
            "寝られない", "ねられない", "cannot sleep", "",
            "I can't sleep because I drank too much coffee."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "勉強", "べんきょう", "study", "",
            "を", "", "object marker", "no-mask",
            "始めた", "はじめた", "started", "",
            "ばかりです", "", "just", "",
            "I've just started studying Japanese."
        ],
        [
            "友達", "ともだち", "friend", "",
            "に", "", "to", "no-mask",
            "プレゼント", "ぷれぜんと", "present", "",
            "を", "", "object marker", "no-mask",
            "あげよう", "", "let's give", "",
            "と", "", "quotation particle", "no-mask",
            "思います", "おもいます", "think", "",
            "I think we should give a present to our friend."
        ],
        [
            "もう", "", "already", "",
            "宿題", "しゅくだい", "homework", "",
            "を", "", "object marker", "no-mask",
            "終わらせて", "おわらせて", "finish", "",
            "しまった", "", "completed", "",
            "か", "", "question particle", "no-mask",
            "Have you already finished your homework?"
        ],
        [
            "宿題", "しゅくだい", "homework", "",
            "やって", "", "do", "",
            "しまった", "", "completed", "",
            "？", "", "question particle", "no-mask",
            "Did you finish your homework?"
        ],
        [
            "映画", "えいが", "movie", "",
            "見に", "みに", "to watch", "",
            "行こう", "いこう", "let's go", "",
            "よ", "", "emphasis", "no-mask",
            "Let's go watch a movie!"
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "上手に", "じょうずに", "skillfully", "",
            "話せる", "はなせる", "can speak", "",
            "ようになりたいな", "", "want to become able to", "",
            "I wanna be able to speak Japanese well."
        ],
        [
            "新しい", "あたらしい", "new", "",
            "バイト", "ばいと", "part-time job", "",
            "始める", "はじめる", "start", "",
            "ことに", "", "to do", "",
            "なったんだ", "", "became", "",
            "I'm gonna start a new part-time job."
        ],
        [
            "雨", "あめ", "rain", "",
            "降る", "ふる", "fall", "",
            "かもね", "", "might", "",
            "It might rain, you know."
        ],
        [
            "この", "", "this", "",
            "本", "ほん", "book", "",
            "読んで", "よんで", "read", "",
            "みない", "", "won't you try", "",
            "？", "", "question particle", "no-mask",
            "Why don't you try reading this book?"
        ],
        [
            "友達", "ともだち", "friend", "",
            "に", "", "to", "no-mask",
            "会う", "あう", "meet", "",
            "はず", "", "supposed to", "",
            "だった", "", "was", "",
            "のに", "", "but...", "no-mask",
            "I was supposed to meet my friend, but..."
        ],
        [
            "宿題", "しゅくだい", "homework", "",
            "忘れちゃった", "わすれちゃった", "forgot", "",
            "よ", "", "emphasis", "no-mask",
            "I totally forgot about the homework!"
        ],
        [
            "明日", "あした", "tomorrow", "",
            "までに", "", "by", "no-mask",
            "レポート", "れぽーと", "report", "",
            "書かなきゃ", "かかなきゃ", "gotta write", "",
            "I gotta write the report by tomorrow."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "テスト", "てすと", "test", "",
            "の", "", "possessive particle", "no-mask",
            "準備", "じゅんび", "preparation", "",
            "しといた", "", "did in advance", "",
            "んだ", "", "explanation", "no-mask",
            "I've already prepared for the Japanese test."
        ]
    ],

    "LEVEL-3": [
        [
            "雨", "あめ", "rain", "",
            "が", "", "subject particle", "no-mask",
            "降り", "ふり", "fall", "",
            "続ける", "つづける", "continue", "",
            "ほど", "", "to the extent that", "no-mask",
            "心", "こころ", "heart", "",
            "が", "", "subject particle", "no-mask",
            "重く", "おもく", "heavy", "",
            "なった", "", "became", "",
            "My heart grew heavier as the rain continued to fall."
        ],
        [
            "夢", "ゆめ", "dream", "",
            "を", "", "object particle", "no-mask",
            "叶える", "かなえる", "fulfill", "",
            "ために", "", "in order to", "no-mask",
            "毎日", "まいにち", "every day", "",
            "頑張って", "がんばって", "work hard", "",
            "いる", "", "progressive", "",
            "I'm working hard every day in order to fulfill my dream."
        ],
        [
            "春", "はる", "spring", "",
            "の", "", "possessive particle", "no-mask",
            "風", "かぜ", "wind", "",
            "が", "", "subject particle", "no-mask",
            "吹く", "ふく", "blow", "",
            "ように", "", "as if", "",
            "なった", "", "became", "",
            "It's become as if the spring wind is blowing."
        ],
        [
            "本", "ほん", "book", "",
            "を", "", "object particle", "no-mask",
            "読み", "よみ", "read", "",
            "終わって", "おわって", "finish", "",
            "しまった", "", "regrettably", "",
            "I regrettably finished reading the book (and have no more to read)."
        ],
        [
            "空", "そら", "sky", "",
            "を", "", "object particle", "no-mask",
            "見上げる", "みあげる", "look up", "",
            "と", "", "when", "",
            "星", "ほし", "star", "",
            "が", "", "subject particle", "no-mask",
            "輝いて", "かがやいて", "shine", "",
            "いた", "", "past progressive", "",
            "When I looked up at the sky, stars were shining."
        ],
        [
            "友達", "ともだち", "friend", "",
            "と", "", "with", "",
            "話す", "はなす", "talk", "",
            "につれて", "", "as", "",
            "気分", "きぶん", "mood", "",
            "が", "", "subject particle", "no-mask",
            "良く", "よく", "good", "",
            "なった", "", "became", "",
            "As I talked with my friend, my mood improved."
        ],
        [
            "山", "やま", "mountain", "",
            "に", "", "to", "no-mask",
            "登る", "のぼる", "climb", "",
            "ことに", "", "to do", "",
            "した", "", "decided", "",
            "I decided to climb the mountain."
        ],
        [
            "花", "はな", "flower", "",
            "が", "", "subject particle", "no-mask",
            "咲く", "さく", "bloom", "",
            "のを", "", "object marker", "",
            "待ちきれない", "まちきれない", "can't wait", "",
            "I can't wait for the flowers to bloom."
        ],
        [
            "音楽", "おんがく", "music", "",
            "を", "", "object particle", "no-mask",
            "聴いて", "きいて", "listen", "",
            "いる", "", "progressive", "",
            "うちに", "", "while", "",
            "眠く", "ねむく", "sleepy", "",
            "なった", "", "became", "",
            "I became sleepy while listening to music."
        ],
        [
            "時間", "じかん", "time", "",
            "が", "", "subject particle", "no-mask",
            "経つ", "たつ", "pass", "",
            "につれて", "", "as", "",
            "思い出", "おもいで", "memory", "",
            "が", "", "subject particle", "no-mask",
            "薄れて", "うすれて", "fade", "",
            "いく", "", "go", "",
            "As time passes, memories fade away."
        ],
        [
            "雪", "ゆき", "snow", "",
            "が", "", "subject particle", "no-mask",
            "降り", "ふり", "fall", "",
            "始めた", "はじめた", "began", "",
            "ので", "", "because", "",
            "帰ろう", "かえろう", "let's go home", "",
            "Because it started snowing, let's go home."
        ],
        [
            "日記", "にっき", "diary", "",
            "を", "", "object particle", "no-mask",
            "書く", "かく", "write", "",
            "ようにして", "", "make it a habit", "",
            "いる", "", "progressive", "",
            "I'm making it a habit to write in my diary."
        ],
        [
            "彼", "かれ", "he", "",
            "の", "", "possessive particle", "no-mask",
            "話", "はなし", "story", "",
            "を", "", "object particle", "no-mask",
            "聞いた", "きいた", "heard", "",
            "ばかり", "", "just", "",
            "です", "", "polite copula", "",
            "I've just heard his story."
        ],
        [
            "窓", "まど", "window", "",
            "を", "", "object particle", "no-mask",
            "開けて", "あけて", "open", "",
            "みると", "", "when try", "",
            "鳥", "とり", "bird", "",
            "の", "", "possessive particle", "no-mask",
            "歌", "うた", "song", "",
            "が", "", "subject particle", "no-mask",
            "聞こえた", "きこえた", "could be heard", "",
            "When I tried opening the window, I could hear birds singing."
        ],
        [
            "新しい", "あたらしい", "new", "",
            "言葉", "ことば", "word", "",
            "を", "", "object particle", "no-mask",
            "覚える", "おぼえる", "memorize", "",
            "たびに", "", "every time", "",
            "世界", "せかい", "world", "",
            "が", "", "subject particle", "no-mask",
            "広がる", "ひろがる", "expand", "",
            "Every time I memorize a new word, my world expands."
        ],
        [
            "夢", "ゆめ", "dream", "",
            "を", "", "object particle", "no-mask",
            "見た", "みた", "saw", "",
            "ような", "", "as if", "",
            "気", "き", "feeling", "",
            "がする", "", "have a feeling", "",
            "I have a feeling as if I saw a dream."
        ],
        [
            "木々", "きぎ", "trees", "",
            "の", "", "possessive particle", "no-mask",
            "間", "あいだ", "between", "",
            "を", "", "object particle", "no-mask",
            "歩いて", "あるいて", "walk", "",
            "いく", "", "go", "",
            "うちに", "", "while", "",
            "心", "こころ", "heart", "",
            "が", "", "subject particle", "no-mask",
            "落ち着いた", "おちついた", "calmed down", "",
            "As I walked among the trees, my heart calmed down."
        ],
        [
            "空", "そら", "sky", "",
            "が", "", "subject particle", "no-mask",
            "青く", "あおく", "blue", "",
            "なれば", "", "if become", "",
            "なるほど", "", "the more", "",
            "心", "こころ", "heart", "",
            "が", "", "subject particle", "no-mask",
            "晴れる", "はれる", "clear up", "",
            "The bluer the sky becomes, the more my heart clears up."
        ],
        [
            "海", "うみ", "sea", "",
            "を", "", "object particle", "no-mask",
            "眺めて", "ながめて", "gaze at", "",
            "いる", "", "progressive", "",
            "と", "", "when", "",
            "時間", "じかん", "time", "",
            "が", "", "subject particle", "no-mask",
            "止まった", "とまった", "stopped", "",
            "ように", "", "as if", "",
            "感じる", "かんじる", "feel", "",
            "When I gaze at the sea, I feel as if time has stopped."
        ],
        [
            "彼女", "かのじょ", "she", "",
            "の", "", "possessive particle", "no-mask",
            "笑顔", "えがお", "smile", "",
            "を", "", "object particle", "no-mask",
            "見る", "みる", "see", "",
            "たびに", "", "every time", "",
            "幸せ", "しあわせ", "happiness", "",
            "を", "", "object particle", "no-mask",
            "感じる", "かんじる", "feel", "",
            "Every time I see her smile, I feel happiness."
        ],
        [
            "月", "つき", "moon", "",
            "が", "", "subject particle", "no-mask",
            "出て", "でて", "come out", "",
            "くる", "", "come", "",
            "につれて", "", "as", "",
            "静けさ", "しずけさ", "quietness", "",
            "が", "", "subject particle", "no-mask",
            "広がった", "ひろがった", "spread", "",
            "As the moon came out, quietness spread."
        ],
        [
            "風", "かぜ", "wind", "",
            "に", "", "by", "no-mask",
            "揺れる", "ゆれる", "sway", "",
            "木々", "きぎ", "trees", "",
            "を", "", "object particle", "no-mask",
            "見て", "みて", "watch", "",
            "いると", "", "when", "",
            "心", "こころ", "heart", "",
            "が", "", "subject particle", "no-mask",
            "和む", "なごむ", "be soothed", "",
            "When I watch the trees swaying in the wind, my heart is soothed."
        ],
        [
            "本", "ほん", "book", "",
            "を", "", "object particle", "no-mask",
            "読み", "よみ", "read", "",
            "終える", "おえる", "finish", "",
            "たびに", "", "every time", "",
            "新しい", "あたらしい", "new", "",
            "世界", "せかい", "world", "",
            "を", "", "object particle", "no-mask",
            "知った", "しった", "learned", "",
            "気", "き", "feeling", "",
            "がする", "", "have a feeling", "",
            "Every time I finish reading a book, I feel like I've learned about a new world."
        ],
        [
            "雨", "あめ", "rain", "",
            "が", "", "subject particle", "no-mask",
            "降り", "ふり", "fall", "",
            "始めた", "はじめた", "began", "",
            "ので", "", "because", "",
            "傘", "かさ", "umbrella", "",
            "を", "", "object particle", "no-mask",
            "さして", "", "open", "",
            "いこう", "", "let's go", "",
            "Because it started raining, let's go with our umbrellas open."
        ],
        [
            "夜", "よる", "night", "",
            "が", "", "subject particle", "no-mask",
            "明ける", "あける", "break", "",
            "まで", "", "until", "",
            "星", "ほし", "star", "",
            "を", "", "object particle", "no-mask",
            "眺めて", "ながめて", "gaze at", "",
            "いた", "", "was", "",
            "I was gazing at the stars until dawn broke."
        ]
    ],

    "LEVEL-4": [
        [
            "この", "", "this", "",
            "映画", "えいが", "movie", "",
            "、", "", "comma", "no-mask",
            "面白くて", "おもしろくて", "interesting", "",
            "たまらない", "", "can't help", "",
            "ね", "", "right?", "no-mask",
            "This movie is so interesting, I can't help but enjoy it, right?"
        ],
        [
            "彼", "かれ", "he", "",
            "が", "", "subject particle", "no-mask",
            "そんな", "", "such", "",
            "こと", "", "thing", "",
            "を", "", "object particle", "no-mask",
            "言う", "いう", "say", "",
            "わけがない", "", "there's no way", "",
            "よ", "", "emphasis", "no-mask",
            "There's no way he would say such a thing!"
        ],
        [
            "今度", "こんど", "next time", "",
            "の", "", "possessive particle", "no-mask",
            "休み", "やすみ", "holiday", "",
            "に", "", "on", "no-mask",
            "旅行", "りょこう", "trip", "",
            "に", "", "to", "no-mask",
            "行く", "いく", "go", "",
            "つもり", "", "intend to", "",
            "なんだ", "", "it is that", "no-mask",
            "I intend to go on a trip during the next holiday."
        ],
        [
            "この", "", "this", "",
            "まま", "", "as it is", "",
            "だと", "", "if", "no-mask",
            "、", "", "comma", "no-mask",
            "遅刻", "ちこく", "late", "",
            "する", "", "do", "",
            "かもしれない", "", "might", "",
            "ね", "", "right?", "no-mask",
            "At this rate, we might be late, don't you think?"
        ],
        [
            "来月", "らいげつ", "next month", "",
            "から", "", "from", "no-mask",
            "新しい", "あたらしい", "new", "",
            "仕事", "しごと", "job", "",
            "を", "", "object particle", "no-mask",
            "始める", "はじめる", "start", "",
            "ことに", "", "it has been decided", "",
            "なった", "", "became", "",
            "んだ", "", "explanation", "no-mask",
            "It's been decided that I'll start a new job from next month."
        ],
        [
            "ドア", "どあ", "door", "",
            "を", "", "object particle", "no-mask",
            "開けよう", "あけよう", "try to open", "",
            "とした", "", "tried to", "",
            "ら", "", "when", "no-mask",
            "、", "", "comma", "no-mask",
            "鍵", "かぎ", "key", "",
            "が", "", "subject particle", "no-mask",
            "かかって", "", "locked", "",
            "いた", "", "was", "",
            "When I tried to open the door, it was locked."
        ],
        [
            "君", "きみ", "you", "",
            "の", "", "possessive particle", "no-mask",
            "アドバイス", "あどばいす", "advice", "",
            "の", "", "possessive particle", "no-mask",
            "おかげで", "", "thanks to", "",
            "試験", "しけん", "exam", "",
            "に", "", "in", "no-mask",
            "合格", "ごうかく", "pass", "",
            "できた", "", "was able to", "",
            "んだ", "", "explanation", "no-mask",
            "Thanks to your advice, I was able to pass the exam."
        ],
        [
            "彼", "かれ", "he", "",
            "なら", "", "if it's", "no-mask",
            "、", "", "comma", "no-mask",
            "もう", "", "already", "",
            "家", "いえ", "home", "",
            "に", "", "to", "no-mask",
            "着いて", "ついて", "arrive", "",
            "いる", "", "being", "",
            "はず", "", "should be", "",
            "だよ", "", "I'm sure", "no-mask",
            "He should have arrived home by now, I'm sure."
        ],
        [
            "雨", "あめ", "rain", "",
            "が", "", "subject particle", "no-mask",
            "降って", "ふって", "fall", "",
            "いる", "", "is", "",
            "としても", "", "even if", "",
            "、", "", "comma", "no-mask",
            "出かける", "でかける", "go out", "",
            "つもり", "", "intend to", "",
            "です", "", "polite copula", "",
            "Even if it's raining, I intend to go out."
        ],
        [
            "それ", "", "that", "",
            "は", "", "topic particle", "no-mask",
            "冗談", "じょうだん", "joke", "",
            "に", "", "to", "no-mask",
            "過ぎない", "", "nothing more than", "",
            "よ", "", "emphasis", "no-mask",
            "That's nothing more than a joke, you know."
        ],
        [
            "この", "", "this", "",
            "本", "ほん", "book", "",
            "、", "", "comma", "no-mask",
            "面白くて", "おもしろくて", "interesting", "",
            "読む", "よむ", "read", "",
            "のを", "", "object marker", "no-mask",
            "やめられない", "", "can't stop", "",
            "んだ", "", "explanation", "no-mask",
            "This book is so interesting, I can't stop reading it."
        ],
        [
            "彼女", "かのじょ", "she", "",
            "が", "", "subject particle", "no-mask",
            "来る", "くる", "come", "",
            "わけがない", "", "there's no way", "",
            "でしょう", "", "probably", "no-mask",
            "There's no way she would come, right?"
        ],
        [
            "明日", "あした", "tomorrow", "",
            "は", "", "topic particle", "no-mask",
            "早く", "はやく", "early", "",
            "起きる", "おきる", "wake up", "",
            "つもり", "", "intend to", "",
            "なんだけど", "", "but", "no-mask",
            "I intend to wake up early tomorrow, but..."
        ],
        [
            "そんな", "", "such", "",
            "こと", "", "thing", "",
            "を", "", "object particle", "no-mask",
            "言えば", "いえば", "if say", "",
            "、", "", "comma", "no-mask",
            "怒る", "おこる", "get angry", "",
            "かもしれない", "", "might", "",
            "よ", "", "emphasis", "no-mask",
            "If you say such a thing, they might get angry, you know."
        ],
        [
            "来週", "らいしゅう", "next week", "",
            "から", "", "from", "no-mask",
            "ダイエット", "だいえっと", "diet", "",
            "を", "", "object particle", "no-mask",
            "始める", "はじめる", "start", "",
            "ことに", "", "it has been decided", "",
            "したんだ", "", "decided", "no-mask",
            "I've decided to start a diet from next week."
        ],
        [
            "財布", "さいふ", "wallet", "",
            "を", "", "object particle", "no-mask",
            "取り出そう", "とりだそう", "try to take out", "",
            "としたら", "", "when tried to", "",
            "、", "", "comma", "no-mask",
            "なくなって", "", "gone", "",
            "いた", "", "was", "",
            "んだ", "", "explanation", "no-mask",
            "When I tried to take out my wallet, it was gone."
        ],
        [
            "君", "きみ", "you", "",
            "の", "", "possessive particle", "no-mask",
            "サポート", "さぽーと", "support", "",
            "の", "", "possessive particle", "no-mask",
            "おかげで", "", "thanks to", "",
            "プロジェクト", "ぷろじぇくと", "project", "",
            "が", "", "subject particle", "no-mask",
            "成功", "せいこう", "success", "",
            "した", "", "did", "",
            "んだ", "", "explanation", "no-mask",
            "Thanks to your support, the project was a success."
        ],
        [
            "彼", "かれ", "he", "",
            "なら", "", "if it's", "no-mask",
            "、", "", "comma", "no-mask",
            "きっと", "", "surely", "",
            "問題", "もんだい", "problem", "",
            "を", "", "object particle", "no-mask",
            "解決", "かいけつ", "solve", "",
            "する", "", "do", "",
            "はず", "", "should", "",
            "だよ", "", "I'm sure", "no-mask",
            "If it's him, he should surely solve the problem."
        ],
        [
            "雪", "ゆき", "snow", "",
            "が", "", "subject particle", "no-mask",
            "降って", "ふって", "fall", "",
            "いる", "", "is", "",
            "としても", "", "even if", "",
            "、", "", "comma", "no-mask",
            "予定", "よてい", "plan", "",
            "通り", "どおり", "as scheduled", "",
            "行く", "いく", "go", "",
            "よ", "", "emphasis", "no-mask",
            "Even if it's snowing, I'll go as planned."
        ],
        [
            "それ", "", "that", "",
            "は", "", "topic particle", "no-mask",
            "ただ", "", "just", "",
            "の", "", "possessive particle", "no-mask",
            "うわさ", "", "rumor", "",
            "に", "", "to", "no-mask",
            "過ぎない", "", "nothing more than", "",
            "と", "", "that", "no-mask",
            "思う", "おもう", "think", "",
            "I think that's nothing more than just a rumor."
        ],
        [
            "この", "", "this", "",
            "ゲーム", "げーむ", "game", "",
            "、", "", "comma", "no-mask",
            "やめられなくて", "", "can't stop", "",
            "困って", "こまって", "troubled", "",
            "いる", "", "being", "",
            "んだ", "", "explanation", "no-mask",
            "I'm troubled because I can't stop playing this game."
        ],
        [
            "彼", "かれ", "he", "",
            "が", "", "subject particle", "no-mask",
            "そんな", "", "such", "",
            "こと", "", "thing", "",
            "を", "", "object particle", "no-mask",
            "知って", "しって", "know", "",
            "いる", "", "being", "",
            "わけがない", "", "there's no way", "",
            "でしょう", "", "probably", "no-mask",
            "There's no way he would know such a thing, right?"
        ],
        [
            "今度", "こんど", "next time", "",
            "の", "", "possessive particle", "no-mask",
            "パーティー", "ぱーてぃー", "party", "",
            "に", "", "to", "no-mask",
            "行く", "いく", "go", "",
            "つもり", "", "intend to", "",
            "なの", "", "explanation", "no-mask",
            "？", "", "question particle", "no-mask",
            "Do you intend to go to the next party?"
        ],
        [
            "そんな", "", "such", "",
            "風", "ふう", "way", "",
            "に", "", "in", "no-mask",
            "言えば", "いえば", "if say", "",
            "、", "", "comma", "no-mask",
            "誤解", "ごかい", "misunderstanding", "",
            "される", "", "be done to", "",
            "かもしれない", "", "might", "",
            "よ", "", "emphasis", "no-mask",
            "If you say it that way, you might be misunderstood, you know."
        ],
        [
            "来月", "らいげつ", "next month", "",
            "から", "", "from", "no-mask",
            "新しい", "あたらしい", "new", "",
            "趣味", "しゅみ", "hobby", "",
            "を", "", "object particle", "no-mask",
            "始める", "はじめる", "start", "",
            "ことに", "", "it has been decided", "",
            "したの", "", "decided", "no-mask",
            "I've decided to start a new hobby from next month."
        ]


    ],
    "LEVEL-5": [
        [
            "人間", "にんげん", "human", "",
            "の", "", "possessive particle", "no-mask",
            "脳", "のう", "brain", "",
            "は", "", "topic particle", "no-mask",
            "寝て", "ねて", "sleep", "",
            "いる", "", "progressive", "",
            "間", "あいだ", "during", "",
            "に", "", "at", "no-mask",
            "も", "", "also", "no-mask",
            "活動して", "かつどうして", "active", "",
            "いる", "", "is", "",
            "The human brain is active even while sleeping."
        ],
        [
            "蜂", "はち", "bee", "",
            "は", "", "topic particle", "no-mask",
            "花", "はな", "flower", "",
            "の", "", "possessive particle", "no-mask",
            "色", "いろ", "color", "",
            "を", "", "object particle", "no-mask",
            "見分ける", "みわける", "distinguish", "",
            "ことが", "", "that", "",
            "できる", "", "can", "",
            "というわけではない", "", "it doesn't necessarily mean", "",
            "It doesn't necessarily mean that bees can distinguish flower colors."
        ],
        [
            "地球", "ちきゅう", "Earth", "",
            "の", "", "possessive particle", "no-mask",
            "重力", "じゅうりょく", "gravity", "",
            "に", "", "by", "no-mask",
            "よって", "", "due to", "",
            "人間", "にんげん", "human", "",
            "は", "", "topic particle", "no-mask",
            "年", "ねん", "year", "",
            "と", "", "with", "no-mask",
            "共に", "ともに", "together", "",
            "少し", "すこし", "a little", "",
            "背が", "せが", "height", "",
            "縮む", "ちぢむ", "shrink", "",
            "Due to Earth's gravity, humans shrink a little in height each year."
        ],
        [
            "コアラ", "こあら", "koala", "",
            "は", "", "topic particle", "no-mask",
            "ユーカリ", "ゆーかり", "eucalyptus", "",
            "の", "", "possessive particle", "no-mask",
            "葉", "は", "leaves", "",
            "しか", "", "only", "no-mask",
            "食べない", "たべない", "don't eat", "",
            "ものの", "", "although", "",
            "水", "みず", "water", "",
            "は", "", "topic particle", "no-mask",
            "ほとんど", "", "almost", "",
            "飲まない", "のまない", "don't drink", "",
            "Although koalas only eat eucalyptus leaves, they hardly drink any water."
        ],
        [
            "月", "つき", "moon", "",
            "に", "", "to", "no-mask",
            "着陸した", "ちゃくりくした", "landed", "",
            "とたん", "", "the moment", "",
            "宇宙飛行士", "うちゅうひこうし", "astronaut", "",
            "は", "", "topic particle", "no-mask",
            "地球", "ちきゅう", "Earth", "",
            "が", "", "subject particle", "no-mask",
            "青い", "あおい", "blue", "",
            "と", "", "that", "no-mask",
            "気づいた", "きづいた", "noticed", "",
            "The moment astronauts landed on the moon, they noticed that Earth is blue."
        ],
        [
            "サメ", "さめ", "shark", "",
            "は", "", "topic particle", "no-mask",
            "泳ぎ", "およぎ", "swim", "",
            "ながら", "", "while", "",
            "眠る", "ねむる", "sleep", "",
            "ことが", "", "that", "",
            "できる", "", "can", "",
            "Sharks can sleep while swimming."
        ],
        [
            "雷", "かみなり", "lightning", "",
            "は", "", "topic particle", "no-mask",
            "太陽", "たいよう", "sun", "",
            "より", "", "than", "",
            "熱い", "あつい", "hot", "",
            "にもかかわらず", "", "despite", "no-mask",
            "短い", "みじかい", "short", "",
            "時間", "じかん", "time", "",
            "しか", "", "only", "no-mask",
            "続かない", "つづかない", "doesn't last", "",
            "Despite being hotter than the sun, lightning only lasts for a short time."
        ],
        [
            "蜂蜜", "はちみつ", "honey", "",
            "は", "", "topic particle", "no-mask",
            "腐る", "くさる", "rot", "",
            "まい", "", "won't", "",
            "Honey won't rot."
        ],
        [
            "人類", "じんるい", "humankind", "",
            "は", "", "topic particle", "no-mask",
            "月", "つき", "moon", "",
            "に", "", "to", "no-mask",
            "行った", "いった", "went", "",
            "ばかりでなく", "", "not only", "",
            "火星", "かせい", "Mars", "",
            "にも", "", "to also", "no-mask",
            "行く", "いく", "go", "",
            "計画", "けいかく", "plan", "",
            "を", "", "object particle", "no-mask",
            "立てて", "たてて", "make", "",
            "いる", "", "is", "",
            "Humankind not only went to the moon but is also planning to go to Mars."
        ],
        [
            "オクトパス", "おくとぱす", "octopus", "",
            "は", "", "topic particle", "no-mask",
            "９つ", "ここのつ", "nine", "",
            "の", "", "possessive particle", "no-mask",
            "脳", "のう", "brain", "",
            "を", "", "object particle", "no-mask",
            "持って", "もって", "have", "",
            "いる", "", "is", "",
            "つつ", "", "in the process of", "",
            "ある", "", "being", "",
            "Octopuses are in the process of having nine brains."
        ],
        [
            "地球", "ちきゅう", "Earth", "",
            "の", "", "possessive particle", "no-mask",
            "自転", "じてん", "rotation", "",
            "に", "", "by", "no-mask",
            "よって", "", "due to", "",
            "日", "ひ", "day", "",
            "の", "", "possessive particle", "no-mask",
            "長さ", "ながさ", "length", "",
            "が", "", "subject particle", "no-mask",
            "変わって", "かわって", "change", "",
            "いく", "", "go", "",
            "The length of a day changes due to Earth's rotation."
        ],
        [
            "人間", "にんげん", "human", "",
            "の", "", "possessive particle", "no-mask",
            "体", "からだ", "body", "",
            "は", "", "topic particle", "no-mask",
            "毎日", "まいにち", "every day", "",
            "3億", "さんおく", "300 million", "",
            "個", "こ", "pieces", "",
            "の", "", "possessive particle", "no-mask",
            "細胞", "さいぼう", "cell", "",
            "を", "", "object particle", "no-mask",
            "作り出して", "つくりだして", "produce", "",
            "いる", "", "is", "",
            "The human body produces 300 million new cells every day."
        ],
        [
            "ペンギン", "ぺんぎん", "penguin", "",
            "は", "", "topic particle", "no-mask",
            "飛べない", "とべない", "cannot fly", "",
            "鳥", "とり", "bird", "",
            "だ", "", "is", "no-mask",
            "というわけではない", "", "it doesn't necessarily mean", "",
            "It doesn't necessarily mean that penguins are birds that cannot fly."
        ],
        [
            "人間", "にんげん", "human", "",
            "の", "", "possessive particle", "no-mask",
            "心臓", "しんぞう", "heart", "",
            "は", "", "topic particle", "no-mask",
            "一生", "いっしょう", "lifetime", "",
            "で", "", "in", "no-mask",
            "30億回", "さんじゅうおくかい", "3 billion times", "",
            "以上", "いじょう", "more than", "",
            "鼓動", "こどう", "beat", "",
            "する", "", "do", "",
            "に", "", "to", "no-mask",
            "違いない", "", "must", "",
            "The human heart must beat more than 3 billion times in a lifetime."
        ],
        [
            "アリ", "あり", "ant", "",
            "は", "", "topic particle", "no-mask",
            "自分", "じぶん", "own", "",
            "の", "", "possessive particle", "no-mask",
            "体重", "たいじゅう", "body weight", "",
            "の", "", "possessive particle", "no-mask",
            "50倍", "ごじゅうばい", "50 times", "",
            "を", "", "object particle", "no-mask",
            "持ち上げる", "もちあげる", "lift", "",
            "ことが", "", "that", "",
            "できる", "", "can", "",
            "Ants can lift 50 times their own body weight."
        ],
        [
            "人間", "にんげん", "human", "",
            "の", "", "possessive particle", "no-mask",
            "爪", "つめ", "nail", "",
            "は", "", "topic particle", "no-mask",
            "1秒間", "いちびょうかん", "one second", "",
            "に", "", "in", "no-mask",
            "0.0000001メートル", "れいてんぜろなななななないちめーとる", "0.0000001 meters", "",
            "伸びて", "のびて", "grow", "",
            "いく", "", "go", "",
            "Human nails grow 0.0000001 meters in one second."
        ],
        [
            "地球", "ちきゅう", "Earth", "",
            "の", "", "possessive particle", "no-mask",
            "海", "うみ", "ocean", "",
            "には", "", "in", "no-mask",
            "まだ", "", "still", "",
            "発見", "はっけん", "discovery", "",
            "されて", "", "been", "",
            "いない", "", "not", "",
            "生物", "せいぶつ", "living creature", "",
            "が", "", "subject particle", "no-mask",
            "たくさん", "", "many", "",
            "いる", "", "exist", "",
            "に", "", "to", "no-mask",
            "違いない", "", "must", "",
            "There must be many undiscovered creatures still in Earth's oceans."
        ],
        [
            "カメレオン", "かめれおん", "chameleon", "",
            "は", "", "topic particle", "no-mask",
            "色", "いろ", "color", "",
            "を", "", "object particle", "no-mask",
            "変える", "かえる", "change", "",
            "ばかりでなく", "", "not only", "",
            "目", "め", "eye", "",
            "を", "", "object particle", "no-mask",
            "別々に", "べつべつに", "separately", "",
            "動かす", "うごかす", "move", "",
            "ことも", "", "also", "no-mask",
            "できる", "", "can", "",
            "Chameleons not only change color but can also move their eyes separately."
        ],
        [
            "蜂", "はち", "bee", "",
            "の", "", "possessive particle", "no-mask",
            "羽", "はね", "wing", "",
            "は", "", "topic particle", "no-mask",
            "1秒間", "いちびょうかん", "one second", "",
            "に", "", "in", "no-mask",
            "230回", "にひゃくさんじゅっかい", "230 times", "no-mask",
            "も", "", "as much as", "no-mask",
            "羽ばたく", "はばたく", "flap", "",
            "そうだ", "", "I heard", "",
            "I heard that a bee's wings flap as much as 230 times in one second."
        ],
        [
            "犬", "いぬ", "dog", "",
            "は", "", "topic particle", "no-mask",
            "人間", "にんげん", "human", "",
            "の", "", "possessive particle", "no-mask",
            "感情", "かんじょう", "emotion", "",
            "を", "", "object particle", "no-mask",
            "嗅ぎ分ける", "かぎわける", "distinguish by smell", "",
            "ことが", "", "that", "",
            "できる", "", "can", "",
            "そうだ", "", "I heard", "",
            "I heard that dogs can distinguish human emotions by smell."
        ],
        [
            "地球", "ちきゅう", "Earth", "",
            "の", "", "possessive particle", "no-mask",
            "自転", "じてん", "rotation", "",
            "は", "", "topic particle", "no-mask",
            "徐々に", "じょじょに", "gradually", "",
            "遅く", "おそく", "slow", "",
            "なりつつ", "", "becoming", "",
            "ある", "", "is", "",
            "Earth's rotation is gradually becoming slower."
        ],
        [
            "イルカ", "いるか", "dolphin", "",
            "は", "", "topic particle", "no-mask",
            "片目", "かため", "one eye", "",
            "を", "", "object particle", "no-mask",
            "開けた", "あけた", "open", "",
            "まま", "", "as is", "",
            "眠る", "ねむる", "sleep", "",
            "らしい", "", "it seems", "",
            "It seems that dolphins sleep with one eye open."
        ],
        [
            "蝶", "ちょう", "butterfly", "",
            "の", "", "possessive particle", "no-mask",
            "寿命", "じゅみょう", "lifespan", "",
            "は", "", "topic particle", "no-mask",
            "わずか", "", "merely", "",
            "1か月", "いっかげつ", "one month", "",
            "ほど", "", "about", "",
            "しかない", "", "only", "",
            "A butterfly's lifespan is merely about one month."
        ],
        [
            "月", "つき", "moon", "",
            "は", "", "topic particle", "no-mask",
            "地球", "ちきゅう", "Earth", "",
            "から", "", "from", "no-mask",
            "徐々に", "じょじょに", "gradually", "",
            "遠ざかって", "とおざかって", "moving away", "",
            "いく", "", "going", "",
            "そうだ", "", "I heard", "",
            "I heard that the moon is gradually moving away from Earth."
        ],
        [
            "人間", "にんげん", "human", "",
            "の", "", "possessive particle", "no-mask",
            "体", "からだ", "body", "",
            "には", "", "in", "no-mask",
            "100兆", "ひゃくちょう", "100 trillion", "",
            "個", "こ", "pieces", "",
            "以上", "いじょう", "more than", "",
            "の", "", "possessive particle", "no-mask",
            "細胞", "さいぼう", "cell", "",
            "がある", "", "exist", "",
            "らしい", "", "it seems", "",
            "It seems that there are more than 100 trillion cells in the human body."
        ],
    ],
    "LEVEL-6": [
        [
            "明日", "あした", "tomorrow", "",
            "の", "", "possessive particle", "no-mask",
            "テスト", "てすと", "test", "",
            "のために", "", "for the purpose", "",
            "今晩", "こんばん", "tonight", "",
            "勉強して", "べんきょうして", "study", "",
            "おかなければ", "", "must", "",
            "ならない", "", "have to", "",
            "そうです", "", "I heard", "no-mask",
            "I heard that we have to study tonight for tomorrow's test."
        ],
        [
            "日本", "にほん", "Japan", "",
            "に", "", "to", "no-mask",
            "行く", "いく", "go", "",
            "前に", "まえに", "before", "",
            "日本語", "にほんご", "Japanese", "",
            "を", "", "object marker", "no-mask",
            "勉強して", "べんきょうして", "study", "",
            "おいた", "", "did in advance", "",
            "ほうが", "", "it would be better if", "",
            "いい", "", "good", "",
            "でしょう", "", "probably", "no-mask",
            "It would probably be better if I studied Japanese in advance before going to Japan."
        ],
        [
            "先生", "せんせい", "teacher", "",
            "は", "", "topic marker", "no-mask",
            "宿題", "しゅくだい", "homework", "",
            "を", "", "object marker", "no-mask",
            "忘れた", "わすれた", "forgot", "",
            "学生", "がくせい", "student", "",
            "に", "", "to", "no-mask",
            "明日", "あした", "tomorrow", "",
            "までに", "", "by", "",
            "提出する", "ていしゅつする", "submit", "",
            "ように", "", "in order to", "",
            "言いました", "いいました", "said", "",
            "The teacher told the student who forgot their homework to submit it by tomorrow."
        ],
        [
            "新しい", "あたらしい", "new", "",
            "仕事", "しごと", "job", "",
            "を", "", "object marker", "no-mask",
            "始める", "はじめる", "start", "",
            "ことに", "", "to do", "",
            "なった", "", "became", "",
            "ので", "", "because", "no-mask",
            "引っ越し", "ひっこし", "moving", "",
            "の", "", "possessive particle", "no-mask",
            "準備", "じゅんび", "preparation", "",
            "を", "", "object marker", "no-mask",
            "しておかなければ", "", "must do in advance", "",
            "なりません", "", "have to", "",
            "Because I'm starting a new job, I have to make preparations for moving in advance."
        ],
        [
            "昨日", "きのう", "yesterday", "",
            "の", "", "possessive particle", "no-mask",
            "パーティー", "ぱーてぃー", "party", "",
            "で", "", "at", "no-mask",
            "食べ", "たべ", "eat", "",
            "すぎて", "", "too much", "",
            "しまったため", "", "because", "",
            "今日", "きょう", "today", "",
            "は", "", "topic marker", "no-mask",
            "気分", "きぶん", "feeling", "",
            "が", "", "subject marker", "no-mask",
            "よくない", "", "not good", "",
            "みたいです", "", "seems like", "",
            "It seems like I'm not feeling well today because I ate too much at yesterday's party."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "テスト", "てすと", "test", "",
            "の", "", "possessive particle", "no-mask",
            "結果", "けっか", "result", "",
            "が", "", "subject marker", "no-mask",
            "良かった", "よかった", "was good", "",
            "ので", "", "because", "no-mask",
            "友達", "ともだち", "friends", "",
            "と", "", "with", "no-mask",
            "お祝い", "おいわい", "celebration", "",
            "を", "", "object marker", "no-mask",
            "することに", "", "decided to do", "",
            "しました", "", "did", "",
            "Because the result of my Japanese test was good, I decided to celebrate with my friends."
        ],
        [
            "来週", "らいしゅう", "next week", "",
            "の", "", "possessive particle", "no-mask",
            "旅行", "りょこう", "trip", "",
            "のために", "", "for the purpose of", "",
            "荷物", "にもつ", "luggage", "",
            "を", "", "object marker", "no-mask",
            "準備して", "じゅんびして", "prepare", "",
            "おいた", "", "did in advance", "",
            "ほうが", "", "it would be better if", "",
            "いい", "", "good", "",
            "でしょう", "", "probably", "no-mask",
            "It would probably be better if I prepared my luggage in advance for next week's trip."
        ],
        [
            "母", "はは", "mother", "",
            "に", "", "to", "no-mask",
            "料理", "りょうり", "cooking", "",
            "を", "", "object marker", "no-mask",
            "教えて", "おしえて", "teach", "",
            "もらおう", "", "receive (volitional)", "",
            "と", "", "quotation particle", "no-mask",
            "思って", "おもって", "think", "",
            "いますが", "", "but", "",
            "忙しそう", "いそがしそう", "looks busy", "",
            "なので", "", "because", "no-mask",
            "遠慮して", "えんりょして", "refrain", "",
            "しまいます", "", "end up doing", "",
            "I'm thinking of asking my mother to teach me cooking, but she looks busy, so I end up refraining from asking."
        ],
        [
            "友達", "ともだち", "friend", "",
            "が", "", "subject marker", "no-mask",
            "海外", "かいがい", "overseas", "",
            "に", "", "to", "no-mask",
            "引っ越す", "ひっこす", "move", "",
            "そうです", "", "I heard", "no-mask",
            "から", "", "because", "no-mask",
            "送別会", "そうべつかい", "farewell party", "",
            "を", "", "object marker", "no-mask",
            "開く", "ひらく", "hold", "",
            "ことに", "", "to do", "",
            "しました", "", "decided", "",
            "I heard that my friend is moving overseas, so I decided to hold a farewell party."
        ],
        [
            "毎日", "まいにち", "every day", "",
            "運動", "うんどう", "exercise", "",
            "する", "", "do", "",
            "ように", "", "in order to", "",
            "なれば", "", "if become", "",
            "健康", "けんこう", "health", "",
            "が", "", "subject marker", "no-mask",
            "良く", "よく", "good", "",
            "なる", "", "become", "",
            "かもしれません", "", "might", "no-mask",
            "If I become able to exercise every day, my health might improve."
        ],
        [
            "先週", "せんしゅう", "last week", "",
            "の", "", "possessive particle", "no-mask",
            "試験", "しけん", "exam", "",
            "の", "", "possessive particle", "no-mask",
            "結果", "けっか", "result", "",
            "が", "", "subject marker", "no-mask",
            "良くなかった", "よくなかった", "was not good", "",
            "ので", "", "because", "no-mask",
            "次", "つぎ", "next", "",
            "は", "", "topic marker", "no-mask",
            "もっと", "", "more", "",
            "頑張らなければ", "がんばらなければ", "must try hard", "",
            "なりません", "", "have to", "",
            "Because the result of last week's exam was not good, I have to try harder next time."
        ],
        [
            "日本", "にほん", "Japan", "",
            "に", "", "to", "no-mask",
            "行く", "いく", "go", "",
            "前に", "まえに", "before", "",
            "日本語", "にほんご", "Japanese", "",
            "を", "", "object marker", "no-mask",
            "勉強して", "べんきょうして", "study", "",
            "おいた", "", "did in advance", "",
            "のに", "", "despite", "no-mask",
            "全然", "ぜんぜん", "not at all", "",
            "話せませんでした", "はなせませんでした", "could not speak", "",
            "Despite studying Japanese in advance before going to Japan, I couldn't speak at all."
        ],
        [
            "新しい", "あたらしい", "new", "",
            "スマートフォン", "すまーとふぉん", "smartphone", "",
            "を", "", "object marker", "no-mask",
            "買おう", "かおう", "buy (volitional)", "",
            "と", "", "quotation particle", "no-mask",
            "思って", "おもって", "think", "",
            "いる", "", "progressive", "",
            "んですが", "", "explanation", "",
            "どの", "", "which", "",
            "モデル", "もでる", "model", "",
            "が", "", "subject marker", "no-mask",
            "いい", "", "good", "",
            "か", "", "whether", "no-mask",
            "迷って", "まよって", "be confused", "",
            "います", "", "am", "",
            "I'm thinking of buying a new smartphone, but I'm confused about which model is good."
        ],
        [
            "昨日", "きのう", "yesterday", "",
            "の", "", "possessive particle", "no-mask",
            "パーティー", "ぱーてぃー", "party", "",
            "で", "", "at", "no-mask",
            "友達", "ともだち", "friend", "",
            "に", "", "to", "no-mask",
            "会う", "あう", "meet", "",
            "はず", "", "supposed to", "",
            "だった", "", "was", "",
            "のに", "", "despite", "no-mask",
            "来なかった", "こなかった", "did not come", "",
            "ので", "", "because", "no-mask",
            "心配", "しんぱい", "worry", "",
            "しています", "", "doing", "",
            "I was supposed to meet my friend at yesterday's party, but they didn't come, so I'm worried."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "授業", "じゅぎょう", "class", "",
            "が", "", "subject marker", "no-mask",
            "始まる", "はじまる", "start", "",
            "前に", "まえに", "before", "",
            "宿題", "しゅくだい", "homework", "",
            "を", "", "object marker", "no-mask",
            "終わらせて", "おわらせて", "finish", "",
            "おこう", "", "let's do in advance", "",
            "と", "", "quotation particle", "no-mask",
            "思います", "おもいます", "think", "",
            "I think I'll finish my homework before the Japanese class starts."
        ],
        [
            "今週末", "こんしゅうまつ", "this weekend", "",
            "友達", "ともだち", "friends", "",
            "と", "", "with", "no-mask",
            "キャンプ", "きゃんぷ", "camping", "",
            "に", "", "to", "no-mask",
            "行く", "いく", "go", "",
            "つもり", "", "intend to", "",
            "でしたが", "", "was, but", "",
            "天気", "てんき", "weather", "",
            "が", "", "subject marker", "no-mask",
            "悪くなりそう", "わるくなりそう", "likely to become bad", "",
            "なので", "", "because", "no-mask",
            "中止", "ちゅうし", "cancellation", "",
            "に", "", "to", "no-mask",
            "しました", "", "did", "",
            "I was intending to go camping with friends this weekend, but because the weather is likely to become bad, I canceled it."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "本", "ほん", "book", "",
            "を", "", "object marker", "no-mask",
            "読み", "よみ", "read", "",
            "ながら", "", "while", "",
            "新しい", "あたらしい", "new", "",
            "単語", "たんご", "vocabulary", "",
            "を", "", "object marker", "no-mask",
            "覚えよう", "おぼえよう", "try to memorize", "",
            "と", "", "quotation particle", "no-mask",
            "しています", "", "doing", "",
            "I'm trying to memorize new vocabulary while reading a Japanese book."
        ],
        [
            "友達", "ともだち", "friend", "",
            "の", "", "possessive particle", "no-mask",
            "誕生日", "たんじょうび", "birthday", "",
            "プレゼント", "ぷれぜんと", "present", "",
            "を", "", "object marker", "no-mask",
            "買い", "かい", "buy", "",
            "に", "", "to", "no-mask",
            "行った", "いった", "went", "",
            "のですが", "", "explanation", "",
            "何", "なに", "what", "",
            "を", "", "object marker", "no-mask",
            "選べば", "えらべば", "if choose", "",
            "いい", "", "good", "",
            "か", "", "whether", "no-mask",
            "分かりません", "わかりません", "don't know", "",
            "I went to buy a birthday present for my friend, but I don't know what I should choose."
        ],
        [
            "先生", "せんせい", "teacher", "",
            "に", "", "to", "no-mask",
            "質問", "しつもん", "question", "",
            "を", "", "object marker", "no-mask",
            "したい", "", "want to do", "",
            "んですが", "", "explanation", "",
            "忙しそう", "いそがしそう", "looks busy", "",
            "なので", "", "because", "no-mask",
            "後で", "あとで", "later", "",
            "聞く", "きく", "ask", "",
            "ことに", "", "to do", "",
            "します", "", "will do", "",
            "I want to ask the teacher a question, but because they look busy, I'll ask later."
        ],
        [
            "来月", "らいげつ", "next month", "",
            "から", "", "from", "no-mask",
            "新しい", "あたらしい", "new", "",
            "仕事", "しごと", "job", "",
            "を", "", "object marker", "no-mask",
            "始める", "はじめる", "start", "",
            "ことに", "", "to do", "",
            "なりました", "", "became", "",
            "が", "", "but", "no-mask",
            "少し", "すこし", "a little", "",
            "不安", "ふあん", "anxious", "",
            "です", "", "is", "no-mask",
            "I'm starting a new job from next month, but I'm a little anxious."
        ],
    ],
    "LEVEL-7": [
        [
            "締め切り", "しめきり", "deadline", "",
            "が", "", "subject particle", "no-mask",
            "近づいて", "ちかづいて", "approaching", "",
            "いる", "", "is", "",
            "ため", "", "because", "",
            "、", "", "comma", "no-mask",
            "徹夜", "てつや", "all-night", "",
            "で", "", "by", "no-mask",
            "作業", "さぎょう", "work", "",
            "せざるを得ない", "", "have no choice but to", "",
            "Because the deadline is approaching, I have no choice but to work all night."
        ],
        [
            "彼", "かれ", "he", "",
            "は", "", "topic particle", "no-mask",
            "何", "なに", "what", "",
            "も", "", "even", "no-mask",
            "起こらなかった", "おこらなかった", "didn't happen", "",
            "かのように", "", "as if", "",
            "振る舞って", "ふるまって", "behave", "",
            "いた", "", "was", "",
            "He was behaving as if nothing had happened."
        ],
        [
            "日本", "にほん", "Japan", "",
            "に", "", "to", "no-mask",
            "限らず", "", "not limited to", "",
            "、", "", "comma", "no-mask",
            "世界中", "せかいじゅう", "worldwide", "",
            "で", "", "in", "no-mask",
            "人気", "にんき", "popular", "",
            "がある", "", "is", "",
            "Not limited to Japan, it's popular worldwide."
        ],
        [
            "警告", "けいこく", "warning", "",
            "にもかかわらず", "", "despite", "",
            "、", "", "comma", "no-mask",
            "彼", "かれ", "he", "",
            "は", "", "topic particle", "no-mask",
            "危険", "きけん", "dangerous", "",
            "な", "", "attributive", "no-mask",
            "行動", "こうどう", "behavior", "",
            "を", "", "object particle", "no-mask",
            "続けた", "つづけた", "continued", "",
            "Despite the warnings, he continued his dangerous behavior."
        ],
        [
            "そこ", "", "there", "",
            "まで", "", "until", "no-mask",
            "説明", "せつめい", "explanation", "",
            "する", "", "do", "",
            "までもない", "", "no need to go as far as", "",
            "でしょう", "", "probably", "no-mask",
            "There's probably no need to go as far as explaining that."
        ],
        [
            "この", "", "this", "",
            "状況", "じょうきょう", "situation", "",
            "では", "", "in", "no-mask",
            "、", "", "comma", "no-mask",
            "黙って", "だまって", "silently", "",
            "いる", "", "being", "",
            "わけにはいかない", "", "cannot", "",
            "In this situation, I cannot remain silent."
        ],
        [
            "彼", "かれ", "he", "",
            "は", "", "topic particle", "no-mask",
            "遅刻", "ちこく", "being late", "",
            "する", "", "do", "",
            "きらいがある", "", "tend to", "",
            "He tends to be late."
        ],
        [
            "今年", "ことし", "this year", "",
            "の", "", "possessive particle", "no-mask",
            "夏", "なつ", "summer", "",
            "は", "", "topic particle", "no-mask",
            "例年", "れいねん", "normal years", "",
            "より", "", "than", "",
            "暑い", "あつい", "hot", "",
            "であろう", "", "probably", "",
            "This year's summer will probably be hotter than usual."
        ],
        [
            "ドア", "どあ", "door", "",
            "を", "", "object particle", "no-mask",
            "開ける", "あける", "open", "",
            "や", "", "as soon as", "no-mask",
            "いなや", "", "as soon as", "",
            "、", "", "comma", "no-mask",
            "冷たい", "つめたい", "cold", "",
            "風", "かぜ", "wind", "",
            "が", "", "subject particle", "no-mask",
            "吹き込んだ", "ふきこんだ", "blew in", "",
            "As soon as I opened the door, a cold wind blew in."
        ],
        [
            "それ", "", "that", "",
            "は", "", "topic particle", "no-mask",
            "単なる", "たんなる", "mere", "",
            "噂", "うわさ", "rumor", "",
            "に", "", "to", "no-mask",
            "すぎない", "", "nothing more than", "",
            "That's nothing more than a mere rumor."
        ],
        [
            "彼", "かれ", "he", "",
            "は", "", "topic particle", "no-mask",
            "頭", "あたま", "head", "",
            "が", "", "subject particle", "no-mask",
            "良い", "よい", "good", "",
            "ばかりか", "", "not only", "",
            "、", "", "comma", "no-mask",
            "運動", "うんどう", "sports", "",
            "も", "", "also", "no-mask",
            "得意", "とくい", "good at", "",
            "だ", "", "is", "no-mask",
            "He is not only smart but also good at sports."
        ],
        [
            "健康", "けんこう", "health", "",
            "に", "", "to", "no-mask",
            "気", "き", "care", "",
            "を", "", "object particle", "no-mask",
            "つける", "", "pay", "",
            "に越したことはない", "", "there's nothing better than", "",
            "There's nothing better than taking care of your health."
        ],
        [
            "この", "", "this", "",
            "申し出", "もうしで", "offer", "",
            "を", "", "object particle", "no-mask",
            "断る", "ことわる", "refuse", "",
            "ことは", "", "to", "no-mask",
            "できかねます", "", "I'm afraid I cannot", "",
            "I'm afraid I cannot refuse this offer."
        ],
        [
            "彼", "かれ", "he", "",
            "は", "", "topic particle", "no-mask",
            "笑い", "わらい", "laugh", "",
            "つつ", "", "while", "",
            "、", "", "comma", "no-mask",
            "悲しそう", "かなしそう", "sad", "",
            "な", "", "attributive", "no-mask",
            "顔", "かお", "face", "",
            "をして", "", "making", "",
            "いた", "", "was", "",
            "He was making a sad face while laughing."
        ],
        [
            "雨", "あめ", "rain", "",
            "であれ", "", "be it", "",
            "、", "", "comma", "no-mask",
            "雪", "ゆき", "snow", "",
            "であれ", "", "be it", "",
            "、", "", "comma", "no-mask",
            "予定", "よてい", "plan", "",
            "通り", "どおり", "as scheduled", "",
            "行く", "いく", "go", "",
            "つもり", "", "intend to", "",
            "です", "", "polite copula", "",
            "Be it rain or snow, I intend to go as scheduled."
        ],
        [
            "時間", "じかん", "time", "",
            "が", "", "subject particle", "no-mask",
            "なく", "", "not have", "",
            "、", "", "comma", "no-mask",
            "急いで", "いそいで", "hurriedly", "",
            "食べざるを得なかった", "", "had no choice but to eat", "",
            "I had no choice but to eat hurriedly as I didn't have time."
        ],
        [
            "彼女", "かのじょ", "she", "",
            "は", "", "topic particle", "no-mask",
            "何", "なに", "what", "",
            "か", "", "something", "no-mask",
            "隠して", "かくして", "hiding", "",
            "いる", "", "is", "",
            "かのように", "", "as if", "",
            "見えた", "みえた", "looked", "",
            "She looked as if she was hiding something."
        ],
        [
            "日本語", "にほんご", "Japanese language", "",
            "に", "", "to", "no-mask",
            "限らず", "", "not limited to", "",
            "、", "", "comma", "no-mask",
            "外国語", "がいこくご", "foreign language", "",
            "を", "", "object particle", "no-mask",
            "学ぶ", "まなぶ", "learn", "",
            "のは", "", "to", "no-mask",
            "難しい", "むずかしい", "difficult", "",
            "Learning a foreign language is difficult, not limited to Japanese."
        ],
        [
            "努力", "どりょく", "effort", "",
            "した", "", "did", "",
            "にもかかわらず", "", "despite", "",
            "、", "", "comma", "no-mask",
            "結果", "けっか", "result", "",
            "は", "", "topic particle", "no-mask",
            "思わしく", "おもわしく", "satisfactory", "",
            "なかった", "", "was not", "",
            "Despite the effort, the result was not satisfactory."
        ],
        [
            "そこ", "", "there", "",
            "まで", "", "until", "no-mask",
            "心配", "しんぱい", "worry", "",
            "する", "", "do", "",
            "までもない", "", "no need to go as far as", "",
            "と", "", "that", "no-mask",
            "思います", "おもいます", "I think", "",
            "I think there's no need to worry that much."
        ],
        [
            "この", "", "this", "",
            "重要", "じゅうよう", "important", "",
            "な", "", "attributive", "no-mask",
            "仕事", "しごと", "work", "",
            "を", "", "object particle", "no-mask",
            "断る", "ことわる", "refuse", "",
            "わけにはいかない", "", "cannot", "",
            "I cannot refuse this important work."
        ],
        [
            "彼", "かれ", "he", "",
            "は", "", "topic particle", "no-mask",
            "約束", "やくそく", "promise", "",
            "を", "", "object particle", "no-mask",
            "忘れる", "わすれる", "forget", "",
            "きらいがある", "", "tend to", "",
            "He tends to forget promises."
        ],
        [
            "来年", "らいねん", "next year", "",
            "の", "", "possessive particle", "no-mask",
            "景気", "けいき", "economy", "",
            "は", "", "topic particle", "no-mask",
            "良く", "よく", "good", "",
            "なる", "", "become", "",
            "であろう", "", "probably", "",
            "The economy will probably improve next year."
        ],
        [
            "試験", "しけん", "exam", "",
            "が", "", "subject particle", "no-mask",
            "終わる", "おわる", "end", "",
            "や", "", "as soon as", "no-mask",
            "いなや", "", "as soon as", "",
            "、", "", "comma", "no-mask",
            "みんな", "", "everyone", "",
            "で", "", "with", "no-mask",
            "祝杯", "しゅくはい", "celebration toast", "",
            "を", "", "object particle", "no-mask",
            "上げた", "あげた", "raised", "",
            "As soon as the exam ended, everyone raised a toast in celebration."
        ],
        [
            "それ", "", "that", "",
            "は", "", "topic particle", "no-mask",
            "一時的", "いちじてき", "temporary", "",
            "な", "", "attributive", "no-mask",
            "問題", "もんだい", "problem", "",
            "に", "", "to", "no-mask",
            "すぎない", "", "nothing more than", "",
            "That's nothing more than a temporary problem."
        ],
        [
            "彼女", "かのじょ", "she", "",
            "は", "", "topic particle", "no-mask",
            "歌", "うた", "song", "",
            "が", "", "subject particle", "no-mask",
            "上手", "じょうず", "good", "",
            "な", "", "attributive", "no-mask",
            "ばかりか", "", "not only", "",
            "、", "", "comma", "no-mask",
            "作詞", "さくし", "lyric writing", "",
            "も", "", "also", "no-mask",
            "できる", "", "can do", "",
            "She not only sings well but can also write lyrics."
        ],
        [
            "早め", "はやめ", "early", "",
            "に", "", "at", "no-mask",
            "準備", "じゅんび", "preparation", "",
            "する", "", "do", "",
            "に越したことはない", "", "there's nothing better than", "",
            "There's nothing better than preparing early."
        ],
        [
            "その", "", "that", "",
            "質問", "しつもん", "question", "",
            "に", "", "to", "no-mask",
            "今", "いま", "now", "",
            "答える", "こたえる", "answer", "",
            "ことは", "", "to", "no-mask",
            "できかねます", "", "I'm afraid I cannot", "",
            "I'm afraid I cannot answer that question now."
        ],
        [
            "仕事", "しごと", "work", "",
            "を", "", "object particle", "no-mask",
            "する", "", "do", "",
            "つつ", "", "while", "",
            "、", "", "comma", "no-mask",
            "勉強", "べんきょう", "study", "",
            "も", "", "also", "no-mask",
            "している", "", "doing", "",
            "I'm studying while working."
        ]
    ]
}