function sentenceToJSON(compactSentences) {
    return compactSentences.map(sentence => {
        let result = [];
        for (let i = 0; i < sentence.length - 4; i += 4) {
            result.push({ word: sentence[i], reading: sentence[i + 1], definition: sentence[i + 2], mask: sentence[i + 3].length === 0 });
        }
        return { words: result, translation: sentence[sentence.length - 1] };
    });
}

const compactSentences =
{
    "LEVEL-1": [
        [
            "私", "わたし", "I", "",
            "は", "", "topic marker", "no-mask",
            "毎朝", "まいあさ", "every morning", "",
            "コーヒー", "こーひー", "coffee", "",
            "を", "", "object marker", "no-mask",
            "飲みます", "のみます", "drink", "",
            "I drink coffee every morning."
        ],
        [
            "彼女", "かのじょ", "she", "",
            "の", "", "possessive particle", "no-mask",
            "猫", "ねこ", "cat", "",
            "は", "", "topic marker", "no-mask",
            "かわいい", "", "cute", "",
            "Her cat is cute."
        ],
        [
            "日曜日", "にちようび", "Sunday", "",
            "に", "", "time particle", "no-mask",
            "公園", "こうえん", "park", "",
            "で", "", "location particle", "no-mask",
            "遊びましょう", "あそびましょう", "let's play", "",
            "Let's play in the park on Sunday."
        ],
        [
            "このペン", "このぺん", "this pen", "",
            "は", "", "topic marker", "no-mask",
            "青い", "あおい", "blue", "",
            "です", "", "is", "no-mask",
            "This pen is blue."
        ],
        [
            "来月", "らいげつ", "next month", "",
            "日本", "にほん", "Japan", "",
            "に", "", "to", "no-mask",
            "行きます", "いきます", "go", "",
            "I will go to Japan next month."
        ],
        [
            "私", "わたし", "I", "",
            "も", "", "also", "no-mask",
            "行きたい", "いきたい", "want to go", "",
            "です", "", "is", "no-mask",
            "I also want to go."
        ],
        [
            "駅", "えき", "station", "",
            "は", "", "topic marker", "no-mask",
            "ここ", "", "here", "",
            "から", "", "from", "no-mask",
            "近い", "ちかい", "near", "",
            "です", "", "is", "no-mask",
            "The station is near from here."
        ],
        [
            "昨日", "きのう", "yesterday", "",
            "友達", "ともだち", "friend", "",
            "と", "", "with", "no-mask",
            "映画", "えいが", "movie", "",
            "を", "", "object marker", "no-mask",
            "見ました", "みました", "watched", "",
            "I watched a movie with a friend yesterday."
        ],
        [
            "私", "わたし", "I", "",
            "の", "", "possessive particle", "no-mask",
            "誕生日", "たんじょうび", "birthday", "",
            "は", "", "topic marker", "no-mask",
            "五月", "ごがつ", "May", "",
            "です", "", "is", "no-mask",
            "My birthday is in May."
        ],
        [
            "日本語", "にほんご", "Japanese language", "",
            "が", "", "subject marker", "no-mask",
            "上手", "じょうず", "good at", "",
            "に", "", "to", "no-mask",
            "なりたい", "", "want (to) become", "",
            "I want to become good at Japanese."
        ],
        [
            "毎晩", "まいばん", "every night", "",
            "十時", "じゅうじ", "10 o'clock", "",
            "に", "", "at", "no-mask",
            "寝ます", "ねます", "sleep", "",
            "I go to sleep at 10 o'clock every night."
        ],
        [
            "週末", "しゅうまつ", "weekend", "",
            "に", "", "on", "no-mask",
            "何", "なに", "what", "",
            "を", "", "object marker", "no-mask",
            "しますか", "", "do you do?", "",
            "What do you do on weekends?"
        ],
        [
            "このりんご", "", "this apple", "",
            "は", "", "topic marker", "no-mask",
            "甘くない", "あまくない", "not sweet", "",
            "です", "", "is", "no-mask",
            "This apple is not sweet."
        ],
        [
            "家", "いえ", "home", "",
            "に", "", "to", "no-mask",
            "帰る", "かえる", "return", "",
            "時間", "じかん", "time", "",
            "です", "", "is", "no-mask",
            "It's time to return home."
        ],
        [
            "電車", "でんしゃ", "train", "",
            "で", "", "by", "no-mask",
            "学校", "がっこう", "school", "",
            "へ", "", "to", "no-mask",
            "行きます", "いきます", "go", "",
            "I go to school by train."
        ],
        [
            "今日", "きょう", "today", "",
            "は", "", "topic marker", "no-mask",
            "とても", "", "very", "",
            "暑い", "あつい", "hot", "",
            "です", "", "is", "no-mask",
            "Today is very hot."
        ],
        [
            "ゆっくり", "", "slowly", "",
            "話して", "はなして", "speak", "",
            "ください", "", "please", "no-mask",
            "Please speak slowly."
        ],
        [
            "水", "みず", "water", "",
            "を", "", "object marker", "no-mask",
            "飲みたい", "のみたい", "want to drink", "",
            "です", "", "is", "no-mask",
            "I want to drink water."
        ],
        [
            "明日", "あした", "tomorrow", "",
            "雨", "あめ", "rain", "",
            "が", "", "subject marker", "no-mask",
            "降る", "ふる", "fall", "",
            "かもしれません", "", "might", "",
            "It might rain tomorrow."
        ],
        [
            "昼ごはん", "ひるごはん", "lunch", "",
            "を", "", "object marker", "no-mask",
            "食べましょう", "たべましょう", "let's eat", "",
            "Let's eat lunch."
        ],
        [
            "日本", "にほん", "Japan", "",
            "に", "", "in", "no-mask",
            "住んで", "すんで", "live", "",
            "います", "", "am", "no-mask",
            "I live in Japan."
        ],
        [
            "私", "わたし", "I", "",
            "は", "", "topic marker", "no-mask",
            "毎週", "まいしゅう", "every week", "",
            "土曜日", "どようび", "Saturday", "",
            "に", "", "on", "no-mask",
            "友達", "ともだち", "friends", "",
            "と", "", "with", "no-mask",
            "公園", "こうえん", "park", "",
            "で", "", "at", "no-mask",
            "サッカー", "さっかー", "soccer", "",
            "を", "", "object marker", "no-mask",
            "します", "", "do", "",
            "I play soccer with my friends at the park every Saturday."
        ],
        [
            "昨日", "きのう", "yesterday", "",
            "の", "", "possessive particle", "no-mask",
            "晩", "ばん", "evening", "",
            "家族", "かぞく", "family", "",
            "と", "", "with", "no-mask",
            "新しい", "あたらしい", "new", "",
            "レストラン", "れすとらん", "restaurant", "",
            "で", "", "at", "no-mask",
            "おいしい", "", "delicious", "",
            "魚", "さかな", "fish", "",
            "を", "", "object marker", "no-mask",
            "食べました", "たべました", "ate", "",
            "Yesterday evening, I ate delicious fish with my family at a new restaurant."
        ],
        [
            "来週", "らいしゅう", "next week", "",
            "の", "", "possessive particle", "no-mask",
            "月曜日", "げつようび", "Monday", "",
            "から", "", "from", "no-mask",
            "金曜日", "きんようび", "Friday", "",
            "まで", "", "until", "no-mask",
            "毎日", "まいにち", "every day", "",
            "朝", "あさ", "morning", "",
            "九時", "くじ", "9 o'clock", "",
            "に", "", "at", "no-mask",
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "クラス", "くらす", "class", "",
            "が", "", "subject marker", "no-mask",
            "あります", "", "exists", "",
            "From next Monday to Friday, there is a Japanese class every day at 9 o'clock in the morning."
        ],
        [
            "私", "わたし", "I", "",
            "の", "", "possessive particle", "no-mask",
            "部屋", "へや", "room", "",
            "に", "", "in", "no-mask",
            "大きい", "おおきい", "big", "",
            "机", "つくえ", "desk", "",
            "と", "", "and", "no-mask",
            "小さい", "ちいさい", "small", "",
            "椅子", "いす", "chair", "",
            "が", "", "subject marker", "no-mask",
            "あります", "", "there are", "",
            "が", "", "but", "no-mask",
            "本", "ほん", "book", "",
            "は", "", "topic marker", "no-mask",
            "ありません", "", "do not exist", "",
            "In my room, there are a big desk and a small chair, but there are no books."
        ]
    ],
    "LEVEL-2": [
        [
            "明日", "あした", "tomorrow", "",
            "の", "", "possessive particle", "no-mask",
            "テスト", "てすと", "test", "",
            "のために", "", "for the purpose", "",
            "今晩", "こんばん", "tonight", "",
            "勉強して", "べんきょうして", "study", "",
            "おかなければ", "", "must", "",
            "ならない", "", "have to", "",
            "そうです", "", "I heard", "no-mask",
            "I heard that we have to study tonight for tomorrow's test."
        ],
        [
            "新しい", "あたらしい", "new", "",
            "言葉", "ことば", "words", "",
            "を", "", "object marker", "no-mask",
            "覚える", "おぼえる", "memorize", "",
            "ために", "", "in order to", "",
            "毎日", "まいにち", "every day", "",
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "ドラマ", "どらま", "drama", "",
            "を", "", "object marker", "no-mask",
            "見て", "みて", "watch", "",
            "いる", "", "progressive", "",
            "んです", "", "explanation", "",
            "が", "", "but", "no-mask",
            "まだ", "", "still", "",
            "上手に", "じょうずに", "skillfully", "",
            "話せる", "はなせる", "can speak", "",
            "ようになりません", "", "have not become able to", "",
            "I've been watching Japanese dramas every day to memorize new words, but I still haven't become able to speak skillfully."
        ],
        [
            "友達", "ともだち", "friend", "",
            "と", "", "with", "no-mask",
            "映画", "えいが", "movie", "",
            "を", "", "object marker", "no-mask",
            "見に", "みに", "to watch", "",
            "行こう", "いこう", "let's go", "",
            "と", "", "quotation particle", "no-mask",
            "思って", "おもって", "think", "",
            "いた", "", "was", "",
            "のに", "", "despite", "no-mask",
            "急に", "きゅうに", "suddenly", "",
            "仕事", "しごと", "work", "",
            "が", "", "subject marker", "no-mask",
            "入って", "はいって", "come in", "",
            "しまって", "", "regrettably", "",
            "行けなく", "いけなく", "cannot go", "",
            "なって", "", "become", "",
            "しまいました", "", "regrettably did", "",
            "I was thinking of going to watch a movie with my friend, but work suddenly came up, and I regrettably became unable to go."
        ],
        [
            "日本", "にほん", "Japan", "",
            "に", "", "to", "no-mask",
            "行く", "いく", "go", "",
            "前に", "まえに", "before", "",
            "日本語", "にほんご", "Japanese", "",
            "を", "", "object marker", "no-mask",
            "勉強して", "べんきょうして", "study", "",
            "おいた", "", "did in advance", "",
            "ほうが", "", "it would be better if", "",
            "いい", "", "good", "",
            "でしょう", "", "probably", "no-mask",
            "It would probably be better if I studied Japanese in advance before going to Japan."
        ],
        [
            "先生", "せんせい", "teacher", "",
            "は", "", "topic marker", "no-mask",
            "宿題", "しゅくだい", "homework", "",
            "を", "", "object marker", "no-mask",
            "忘れた", "わすれた", "forgot", "",
            "学生", "がくせい", "student", "",
            "に", "", "to", "no-mask",
            "明日", "あした", "tomorrow", "",
            "までに", "", "by", "",
            "提出する", "ていしゅつする", "submit", "",
            "ように", "", "in order to", "",
            "言いました", "いいました", "said", "",
            "The teacher told the student who forgot their homework to submit it by tomorrow."
        ],
        [
            "新しい", "あたらしい", "new", "",
            "仕事", "しごと", "job", "",
            "を", "", "object marker", "no-mask",
            "始める", "はじめる", "start", "",
            "ことに", "", "to do", "",
            "なった", "", "became", "",
            "ので", "", "because", "no-mask",
            "引っ越し", "ひっこし", "moving", "",
            "の", "", "possessive particle", "no-mask",
            "準備", "じゅんび", "preparation", "",
            "を", "", "object marker", "no-mask",
            "しておかなければ", "", "must do in advance", "",
            "なりません", "", "have to", "",
            "Because I'm starting a new job, I have to make preparations for moving in advance."
        ],
        [
            "昨日", "きのう", "yesterday", "",
            "の", "", "possessive particle", "no-mask",
            "パーティー", "ぱーてぃー", "party", "",
            "で", "", "at", "no-mask",
            "食べ", "たべ", "eat", "",
            "すぎて", "", "too much", "",
            "しまったため", "", "because", "",
            "今日", "きょう", "today", "",
            "は", "", "topic marker", "no-mask",
            "気分", "きぶん", "feeling", "",
            "が", "", "subject marker", "no-mask",
            "よくない", "", "not good", "",
            "みたいです", "", "seems like", "",
            "It seems like I'm not feeling well today because I ate too much at yesterday's party."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "テスト", "てすと", "test", "",
            "の", "", "possessive particle", "no-mask",
            "結果", "けっか", "result", "",
            "が", "", "subject marker", "no-mask",
            "良かった", "よかった", "was good", "",
            "ので", "", "because", "no-mask",
            "友達", "ともだち", "friends", "",
            "と", "", "with", "no-mask",
            "お祝い", "おいわい", "celebration", "",
            "を", "", "object marker", "no-mask",
            "することに", "", "decided to do", "",
            "しました", "", "did", "",
            "Because the result of my Japanese test was good, I decided to celebrate with my friends."
        ],
        [
            "来週", "らいしゅう", "next week", "",
            "の", "", "possessive particle", "no-mask",
            "旅行", "りょこう", "trip", "",
            "のために", "", "for the purpose of", "",
            "荷物", "にもつ", "luggage", "",
            "を", "", "object marker", "no-mask",
            "準備して", "じゅんびして", "prepare", "",
            "おいた", "", "did in advance", "",
            "ほうが", "", "it would be better if", "",
            "いい", "", "good", "",
            "でしょう", "", "probably", "no-mask",
            "It would probably be better if I prepared my luggage in advance for next week's trip."
        ],
        [
            "母", "はは", "mother", "",
            "に", "", "to", "no-mask",
            "料理", "りょうり", "cooking", "",
            "を", "", "object marker", "no-mask",
            "教えて", "おしえて", "teach", "",
            "もらおう", "", "receive (volitional)", "",
            "と", "", "quotation particle", "no-mask",
            "思って", "おもって", "think", "",
            "いますが", "", "but", "",
            "忙しそう", "いそがしそう", "looks busy", "",
            "なので", "", "because", "no-mask",
            "遠慮して", "えんりょして", "refrain", "",
            "しまいます", "", "end up doing", "",
            "I'm thinking of asking my mother to teach me cooking, but she looks busy, so I end up refraining from asking."
        ],
        [
            "友達", "ともだち", "friend", "",
            "が", "", "subject marker", "no-mask",
            "海外", "かいがい", "overseas", "",
            "に", "", "to", "no-mask",
            "引っ越す", "ひっこす", "move", "",
            "そうです", "", "I heard", "no-mask",
            "から", "", "because", "no-mask",
            "送別会", "そうべつかい", "farewell party", "",
            "を", "", "object marker", "no-mask",
            "開く", "ひらく", "hold", "",
            "ことに", "", "to do", "",
            "しました", "", "decided", "",
            "I heard that my friend is moving overseas, so I decided to hold a farewell party."
        ],
        [
            "毎日", "まいにち", "every day", "",
            "運動", "うんどう", "exercise", "",
            "する", "", "do", "",
            "ように", "", "in order to", "",
            "なれば", "", "if become", "",
            "健康", "けんこう", "health", "",
            "が", "", "subject marker", "no-mask",
            "良く", "よく", "good", "",
            "なる", "", "become", "",
            "かもしれません", "", "might", "no-mask",
            "If I become able to exercise every day, my health might improve."
        ],
        [
            "先週", "せんしゅう", "last week", "",
            "の", "", "possessive particle", "no-mask",
            "試験", "しけん", "exam", "",
            "の", "", "possessive particle", "no-mask",
            "結果", "けっか", "result", "",
            "が", "", "subject marker", "no-mask",
            "良くなかった", "よくなかった", "was not good", "",
            "ので", "", "because", "no-mask",
            "次", "つぎ", "next", "",
            "は", "", "topic marker", "no-mask",
            "もっと", "", "more", "",
            "頑張らなければ", "がんばらなければ", "must try hard", "",
            "なりません", "", "have to", "",
            "Because the result of last week's exam was not good, I have to try harder next time."
        ],
        [
            "日本", "にほん", "Japan", "",
            "に", "", "to", "no-mask",
            "行く", "いく", "go", "",
            "前に", "まえに", "before", "",
            "日本語", "にほんご", "Japanese", "",
            "を", "", "object marker", "no-mask",
            "勉強して", "べんきょうして", "study", "",
            "おいた", "", "did in advance", "",
            "のに", "", "despite", "no-mask",
            "全然", "ぜんぜん", "not at all", "",
            "話せませんでした", "はなせませんでした", "could not speak", "",
            "Despite studying Japanese in advance before going to Japan, I couldn't speak at all."
        ],
        [
            "新しい", "あたらしい", "new", "",
            "スマートフォン", "すまーとふぉん", "smartphone", "",
            "を", "", "object marker", "no-mask",
            "買おう", "かおう", "buy (volitional)", "",
            "と", "", "quotation particle", "no-mask",
            "思って", "おもって", "think", "",
            "いる", "", "progressive", "",
            "んですが", "", "explanation", "",
            "どの", "", "which", "",
            "モデル", "もでる", "model", "",
            "が", "", "subject marker", "no-mask",
            "いい", "", "good", "",
            "か", "", "whether", "no-mask",
            "迷って", "まよって", "be confused", "",
            "います", "", "am", "",
            "I'm thinking of buying a new smartphone, but I'm confused about which model is good."
        ],
        [
            "昨日", "きのう", "yesterday", "",
            "の", "", "possessive particle", "no-mask",
            "パーティー", "ぱーてぃー", "party", "",
            "で", "", "at", "no-mask",
            "友達", "ともだち", "friend", "",
            "に", "", "to", "no-mask",
            "会う", "あう", "meet", "",
            "はず", "", "supposed to", "",
            "だった", "", "was", "",
            "のに", "", "despite", "no-mask",
            "来なかった", "こなかった", "did not come", "",
            "ので", "", "because", "no-mask",
            "心配", "しんぱい", "worry", "",
            "しています", "", "doing", "",
            "I was supposed to meet my friend at yesterday's party, but they didn't come, so I'm worried."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "授業", "じゅぎょう", "class", "",
            "が", "", "subject marker", "no-mask",
            "始まる", "はじまる", "start", "",
            "前に", "まえに", "before", "",
            "宿題", "しゅくだい", "homework", "",
            "を", "", "object marker", "no-mask",
            "終わらせて", "おわらせて", "finish", "",
            "おこう", "", "let's do in advance", "",
            "と", "", "quotation particle", "no-mask",
            "思います", "おもいます", "think", "",
            "I think I'll finish my homework before the Japanese class starts."
        ],
        [
            "今週末", "こんしゅうまつ", "this weekend", "",
            "友達", "ともだち", "friends", "",
            "と", "", "with", "no-mask",
            "キャンプ", "きゃんぷ", "camping", "",
            "に", "", "to", "no-mask",
            "行く", "いく", "go", "",
            "つもり", "", "intend to", "",
            "でしたが", "", "was, but", "",
            "天気", "てんき", "weather", "",
            "が", "", "subject marker", "no-mask",
            "悪くなりそう", "わるくなりそう", "likely to become bad", "",
            "なので", "", "because", "no-mask",
            "中止", "ちゅうし", "cancellation", "",
            "に", "", "to", "no-mask",
            "しました", "", "did", "",
            "I was intending to go camping with friends this weekend, but because the weather is likely to become bad, I canceled it."
        ],
        [
            "日本語", "にほんご", "Japanese", "",
            "の", "", "possessive particle", "no-mask",
            "本", "ほん", "book", "",
            "を", "", "object marker", "no-mask",
            "読み", "よみ", "read", "",
            "ながら", "", "while", "",
            "新しい", "あたらしい", "new", "",
            "単語", "たんご", "vocabulary", "",
            "を", "", "object marker", "no-mask",
            "覚えよう", "おぼえよう", "try to memorize", "",
            "と", "", "quotation particle", "no-mask",
            "しています", "", "doing", "",
            "I'm trying to memorize new vocabulary while reading a Japanese book."
        ],
        [
            "友達", "ともだち", "friend", "",
            "の", "", "possessive particle", "no-mask",
            "誕生日", "たんじょうび", "birthday", "",
            "プレゼント", "ぷれぜんと", "present", "",
            "を", "", "object marker", "no-mask",
            "買い", "かい", "buy", "",
            "に", "", "to", "no-mask",
            "行った", "いった", "went", "",
            "のですが", "", "explanation", "",
            "何", "なに", "what", "",
            "を", "", "object marker", "no-mask",
            "選べば", "えらべば", "if choose", "",
            "いい", "", "good", "",
            "か", "", "whether", "no-mask",
            "分かりません", "わかりません", "don't know", "",
            "I went to buy a birthday present for my friend, but I don't know what I should choose."
        ],
        [
            "先生", "せんせい", "teacher", "",
            "に", "", "to", "no-mask",
            "質問", "しつもん", "question", "",
            "を", "", "object marker", "no-mask",
            "したい", "", "want to do", "",
            "んですが", "", "explanation", "",
            "忙しそう", "いそがしそう", "looks busy", "",
            "なので", "", "because", "no-mask",
            "後で", "あとで", "later", "",
            "聞く", "きく", "ask", "",
            "ことに", "", "to do", "",
            "します", "", "will do", "",
            "I want to ask the teacher a question, but because they look busy, I'll ask later."
        ],
        [
            "来月", "らいげつ", "next month", "",
            "から", "", "from", "no-mask",
            "新しい", "あたらしい", "new", "",
            "仕事", "しごと", "job", "",
            "を", "", "object marker", "no-mask",
            "始める", "はじめる", "start", "",
            "ことに", "", "to do", "",
            "なりました", "", "became", "",
            "が", "", "but", "no-mask",
            "少し", "すこし", "a little", "",
            "不安", "ふあん", "anxious", "",
            "です", "", "is", "no-mask",
            "I'm starting a new job from next month, but I'm a little anxious."
        ],
    ]
}